<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>f5ebcc65-0fec-406a-9fb7-57d6680be932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='address-form-vue']/div[2]/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>118cafce-0ecd-45b8-8724-50cfacd9fa5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-authorBtn -default block bg-white text-green rounded px-10 md:px-50 w-full text-center mr-8 md:w-auto</value>
      <webElementGuid>bf5f5a64-8d01-44d4-a363-7aa664205034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Cancel
                </value>
      <webElementGuid>6b1771aa-9859-40d6-ab0b-3b1a59f680b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-form-vue&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;flex pb-30 to-xs:justify-between&quot;]/div[@class=&quot;xs:mr-30 text-center to-xs:w-1_2 mr-10&quot;]/button[@class=&quot;a-authorBtn -default block bg-white text-green rounded px-10 md:px-50 w-full text-center mr-8 md:w-auto&quot;]</value>
      <webElementGuid>f690f310-a5b0-42d1-b55f-479515655f1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='address-form-vue']/div[2]/div[2]/div/button</value>
      <webElementGuid>3d7bf8af-4a4e-4cf9-b54e-db919d78c10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make this my Default Shipping Address'])[1]/following::button[1]</value>
      <webElementGuid>148f0641-6f09-4f9e-9b35-4a22a7c90ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Optional)'])[5]/following::button[1]</value>
      <webElementGuid>55ce700e-d406-4d9b-803d-0c10f4e2caec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::button[1]</value>
      <webElementGuid>0bdc862e-1849-477d-9e8d-237dd2931855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City is required'])[3]/preceding::button[2]</value>
      <webElementGuid>5d46cf17-98f3-405e-9f71-470f9e455166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>e4de8b82-9a5a-4c4f-9187-1e7e775698f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button</value>
      <webElementGuid>a9e0f7b0-3ee3-4ec9-abb2-561420be00ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                    Cancel
                ' or . = '
                    Cancel
                ')]</value>
      <webElementGuid>a4d83911-fd04-49e9-82ed-491a30b12ff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
