<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New Products</name>
   <tag></tag>
   <elementGuidId>c8c75f31-e012-4771-90f7-dec8df7bcf77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lvlD3D05F37769743A9926AD31BC95D1283 > li.m-navMenu__item.-lvl2.Both > a.m-navMenu__item-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='m-navMenu__lvl1']/li[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6909bb96-1f03-4d3a-ae6c-70484e8f976b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/productstore/extra-savings/new-products</value>
      <webElementGuid>102e3dbf-cfb7-473d-876c-4b0ab6c380c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>406146fb-4633-40c8-bceb-2e0727ffc772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>e3ebd3eb-a1b6-4185-bcdd-778b96dfea59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cb9259d8-a672-404b-bb39-3c1bb4921c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-navMenu__item-btn</value>
      <webElementGuid>39ebe5aa-1479-4dfe-84d5-ec20e9eeaf9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1358ab2c-2ad9-4808-ae19-b629e7072899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Products </value>
      <webElementGuid>0481fdfb-629c-4306-a841-a3337724846a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lvlD3D05F37769743A9926AD31BC95D1283&quot;)/li[@class=&quot;m-navMenu__item -lvl2 Both&quot;]/a[@class=&quot;m-navMenu__item-btn&quot;]</value>
      <webElementGuid>35d93a86-78dc-4838-a08d-e8177d6d7f0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='lvlD3D05F37769743A9926AD31BC95D1283']/li[3]/a</value>
      <webElementGuid>79f24bb8-57e7-491c-b995-dee849ac7c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New Products')]</value>
      <webElementGuid>288e3e51-8b86-46ad-be6d-b7e5a5348d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extra Savings'])[2]/following::a[1]</value>
      <webElementGuid>6596426a-5928-4281-913a-55ec9effeab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back To Main'])[6]/following::a[2]</value>
      <webElementGuid>d65ef98e-3f17-45a5-89b7-e9cb4af2106a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web-Only'])[1]/preceding::a[1]</value>
      <webElementGuid>9b4ce078-fb1c-45e3-a817-c3b331478bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Super Value'])[1]/preceding::a[2]</value>
      <webElementGuid>99df96a8-051f-4877-b00c-273d7cdc8064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Products']/parent::*</value>
      <webElementGuid>9576cb5c-1dae-4dbd-a57c-ad6acb61e937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/productstore/extra-savings/new-products')]</value>
      <webElementGuid>f104e2a7-4777-47fb-8217-e04cfd48272c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]/div/ul/li[3]/a</value>
      <webElementGuid>8e851c9c-08f9-411d-8152-ff23b943df9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/productstore/extra-savings/new-products' and (text() = 'New Products ' or . = 'New Products ')]</value>
      <webElementGuid>b22c6546-94ca-442a-bee7-6478dd63acc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
