<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_faq_mem_questions</name>
   <tag></tag>
   <elementGuidId>1836f894-a0f1-4caa-b532-4340e684a627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/main/section[1]/div/div/div[1]/nav/ul/li[2]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05ea38bc-469a-47ae-9d9e-a5d59173ef3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://productstore2-uattw.melaleuca.com/help-center/faq/membership/general-membership-questions</value>
      <webElementGuid>709280c3-7886-4c92-9ef3-7233c968cff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>會員常見問題</value>
      <webElementGuid>49be43d0-aac2-4161-a95a-42b6fbd70800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/section[@class=&quot;md:py-40&quot;]/div[@class=&quot;w-full px-10 pt-10 pb-36 mx-auto mt-10 mb-0 bg-white border max-w-contain border-gray-50 text-gray-150 md:mb-40 md:px-40 md:rounded&quot;]/div[@class=&quot;md:flex md:justify-between&quot;]/div[@class=&quot;mb-30 md:mb-6&quot;]/nav[1]/ul[@class=&quot;text-sm font-medium leading-relaxed text-green-100 mr-15 to-md:hidden md:text-md&quot;]/li[@class=&quot;my-24 md:my-3&quot;]/ul[@class=&quot;test&quot;]/li[@class=&quot;text-black border-l-4 border-clear font-normal pl-6 my-24 leading-normal md:my-8&quot;]/a[1]</value>
      <webElementGuid>ecf2d770-3d0f-4fc7-b659-682df36f76a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/section/div/div/div/nav/ul/li[2]/ul/li[3]/a</value>
      <webElementGuid>97125b3c-d2b3-4402-9892-d99aa08327a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'會員常見問題')])[2]</value>
      <webElementGuid>55da59ce-2992-4ca0-95c3-2b7ae2962930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='會員優惠'])[4]/following::a[1]</value>
      <webElementGuid>8a14c5f4-47fa-43f3-b67c-e7529ce8b821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='成為會員'])[2]/following::a[2]</value>
      <webElementGuid>4872c87d-732f-40d4-b084-329c6e6dac77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='業務發展相關訊息'])[1]/preceding::a[1]</value>
      <webElementGuid>35347df1-794e-4eb5-8583-04ddaffdab55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='相關連結'])[1]/preceding::a[2]</value>
      <webElementGuid>06eb0025-66d7-446e-b322-fd57f7798549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://productstore2-uattw.melaleuca.com/help-center/faq/membership/general-membership-questions')])[2]</value>
      <webElementGuid>c790013c-4f32-421c-b4e3-af9dcb098bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[3]/a</value>
      <webElementGuid>fd4a3f85-02ee-4e01-aa3f-43ceb12ad04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://productstore2-uattw.melaleuca.com/help-center/faq/membership/general-membership-questions' and (text() = '會員常見問題' or . = '會員常見問題')]</value>
      <webElementGuid>6dc3429f-d928-4868-94d1-0cf52e63e5ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
