<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_faq</name>
   <tag></tag>
   <elementGuidId>dece2f1c-ff4c-49e6-a15c-1d3f3e19ecab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='footer']/div[2]/div[2]/nav/div[2]/div[2]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6dc9fc9f-200a-4c6d-ba84-8b833b392f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/help-center/faq/customer-service/orders</value>
      <webElementGuid>4a2553dc-66e7-400f-b861-d8bb17742a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-siteFooter__link</value>
      <webElementGuid>8f149328-c028-4452-b920-fbe67c7435eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>常見問與答</value>
      <webElementGuid>50cf7d52-9d68-4345-989d-f8400d3f5fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer&quot;)/div[@class=&quot;o-siteFooter__section -content&quot;]/div[@class=&quot;o-siteFooter__row -content -signedIn&quot;]/nav[@class=&quot;o-siteFooter__col -nav&quot;]/div[@class=&quot;o-siteFooter__nav -right&quot;]/div[@class=&quot;o-siteFooter__navList&quot;]/ul[1]/li[@class=&quot;o-siteFooter__item&quot;]/a[@class=&quot;o-siteFooter__link&quot;]</value>
      <webElementGuid>e69614e1-9585-44d1-95ce-e730cdc39526</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footer']/div[2]/div[2]/nav/div[2]/div[2]/ul/li[3]/a</value>
      <webElementGuid>01532f9b-bf3e-4d87-8eaa-10dc1de4cf37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'常見問與答')]</value>
      <webElementGuid>459d3792-66d9-49bb-a6d0-2528c201e8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='聯絡美樂家'])[4]/following::a[1]</value>
      <webElementGuid>5a488197-fd8c-4ffc-9486-356c4ad1ebe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='事業中心'])[3]/following::a[2]</value>
      <webElementGuid>9e32b3a5-3cd8-4931-aada-42e3bd3efa2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='公告事項'])[1]/preceding::a[1]</value>
      <webElementGuid>17666eea-e61f-43a5-8ffc-2ae38eddd68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tooltip:'])[1]/preceding::a[5]</value>
      <webElementGuid>403b5a69-71b7-4bc9-a9be-bf288cfc70f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='常見問與答']/parent::*</value>
      <webElementGuid>1270d9aa-f468-49a9-8078-e0f24a87f269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/help-center/faq/customer-service/orders')]</value>
      <webElementGuid>97fec1f1-26a5-49c0-85d9-6541c8f21ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/ul/li[3]/a</value>
      <webElementGuid>4f96af7d-fdf5-46b8-b085-0936d1caa8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/help-center/faq/customer-service/orders' and (text() = '常見問與答' or . = '常見問與答')]</value>
      <webElementGuid>52a657c2-7d54-4f60-93eb-b4e1747b70e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
