<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_faq_cs</name>
   <tag></tag>
   <elementGuidId>77af5b85-0276-4a98-a35e-b40ea55f898f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/main/section[1]/div/div/div[1]/nav/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c9111e55-e91a-409b-bd2b-fcc4acac3115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://productstore2-uattw.melaleuca.com/help-center/faq/customer-service/orders</value>
      <webElementGuid>088f8e87-4a92-4a73-863a-cc2abfd9bd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>顧客服務相關訊息</value>
      <webElementGuid>25837ed3-a147-495a-8c2a-8fb4c9141af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/section[@class=&quot;md:py-40&quot;]/div[@class=&quot;w-full px-10 pt-10 pb-36 mx-auto mt-10 mb-0 bg-white border max-w-contain border-gray-50 text-gray-150 md:mb-40 md:px-40 md:rounded&quot;]/div[@class=&quot;md:flex md:justify-between&quot;]/div[@class=&quot;mb-30 md:mb-6&quot;]/nav[1]/ul[@class=&quot;text-sm font-medium leading-relaxed text-green-100 mr-15 to-md:hidden md:text-md&quot;]/li[@class=&quot;my-24 md:my-3&quot;]/a[1]</value>
      <webElementGuid>4eb606e1-5261-4aa8-ac7f-624abafcb25f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/section/div/div/div/nav/ul/li/a</value>
      <webElementGuid>913adbc2-00c7-42f9-ae64-1d3fe786877a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'顧客服務相關訊息')]</value>
      <webElementGuid>e96c5301-4ea1-42a9-84db-c75a857f7936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='常見問與答'])[4]/following::a[1]</value>
      <webElementGuid>680d038d-2544-4d87-a599-d65626381f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='常見問與答'])[3]/following::a[1]</value>
      <webElementGuid>55bf9e22-f97c-4c7f-a11d-dd4c9b5caa8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='訂貨'])[4]/preceding::a[1]</value>
      <webElementGuid>2e4ee93f-beba-4dc1-87e5-6fe41eddd777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='退換貨說明'])[2]/preceding::a[2]</value>
      <webElementGuid>ed3564d9-f5dc-489d-8d41-4f9e8f9282cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='顧客服務相關訊息']/parent::*</value>
      <webElementGuid>cefee403-c4be-4332-a111-aded9d50ae19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://productstore2-uattw.melaleuca.com/help-center/faq/customer-service/orders')])[2]</value>
      <webElementGuid>f8e47ebc-7df2-4bd0-bc39-b0c129f91f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li/a</value>
      <webElementGuid>160bb30a-46cd-4d59-b003-d6e5fe98d22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://productstore2-uattw.melaleuca.com/help-center/faq/customer-service/orders' and (text() = '顧客服務相關訊息' or . = '顧客服務相關訊息')]</value>
      <webElementGuid>02653599-7260-41b7-99b8-e162649706dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
