<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_faq_bd_report</name>
   <tag></tag>
   <elementGuidId>5a2697f6-d903-4d05-91c0-b62ed407ff9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/section/div/div/div/nav/ul/li[3]/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>caf45a51-ef4e-4e29-9861-1eb3ca1ad51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://productstore2-uattw.melaleuca.com/help-center/faq/business-development/reports-tools</value>
      <webElementGuid>7a140bb6-8c84-4508-b203-0a6b03f4c75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>報表＆工具</value>
      <webElementGuid>03f47a14-f269-47c3-a11e-60e2f3419b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/section[@class=&quot;md:py-40&quot;]/div[@class=&quot;w-full px-10 pt-10 pb-36 mx-auto mt-10 mb-0 bg-white border max-w-contain border-gray-50 text-gray-150 md:mb-40 md:px-40 md:rounded&quot;]/div[@class=&quot;md:flex md:justify-between&quot;]/div[@class=&quot;mb-30 md:mb-6&quot;]/nav[1]/ul[@class=&quot;text-sm font-medium leading-relaxed text-green-100 mr-15 to-md:hidden md:text-md&quot;]/li[@class=&quot;my-24 md:my-3&quot;]/ul[@class=&quot;test&quot;]/li[@class=&quot;text-black border-l-4 border-clear font-normal pl-6 my-24 leading-normal md:my-8&quot;]/a[1]</value>
      <webElementGuid>0b8c3d79-9f33-413c-a7d6-d106e1795cf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/section/div/div/div/nav/ul/li[3]/ul/li[5]/a</value>
      <webElementGuid>310cfc3f-f659-4622-9558-f860f61de2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'報表＆工具')])[2]</value>
      <webElementGuid>9ade586c-33ef-4ae3-8f07-706b9c6a4479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='事業相關變動'])[4]/following::a[1]</value>
      <webElementGuid>11760566-f83b-44d4-a137-886b48e95289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='經營自己的事業'])[2]/following::a[2]</value>
      <webElementGuid>468fad3d-884a-4119-835a-7cfa559c1862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='會議＆活動'])[2]/preceding::a[1]</value>
      <webElementGuid>bac1e642-fef2-475b-99b1-aa80ebb271ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='佣金＆稅'])[2]/preceding::a[2]</value>
      <webElementGuid>5c1d5c34-99cb-426e-80ae-11a25a85dbb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://productstore2-uattw.melaleuca.com/help-center/faq/business-development/reports-tools')])[2]</value>
      <webElementGuid>6f0a3ef1-5f96-4be4-9b71-89530dcb66fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[5]/a</value>
      <webElementGuid>651e19fc-4102-4ce0-8dc0-b9a4bcd0373f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://productstore2-uattw.melaleuca.com/help-center/faq/business-development/reports-tools' and (text() = '報表＆工具' or . = '報表＆工具')]</value>
      <webElementGuid>6af08cea-3fe8-4924-b2ba-531c6389dcd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
