<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_faq_cs_orders</name>
   <tag></tag>
   <elementGuidId>638a0db4-e8d6-430f-83a8-609e6dc58f15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/main/section[1]/div/div/div[1]/nav/ul/li[1]/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f781e02-113e-4ff7-b976-4e1ba54a08db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://productstore2-uattw.melaleuca.com/help-center/faq/customer-service/orders</value>
      <webElementGuid>21fce636-0494-4cc0-9342-ee45abdfa2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>訂貨</value>
      <webElementGuid>623b4c6f-72f8-420c-bd00-e2c9bd7dcdc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/section[@class=&quot;md:py-40&quot;]/div[@class=&quot;w-full px-10 pt-10 pb-36 mx-auto mt-10 mb-0 bg-white border max-w-contain border-gray-50 text-gray-150 md:mb-40 md:px-40 md:rounded&quot;]/div[@class=&quot;md:flex md:justify-between&quot;]/div[@class=&quot;mb-30 md:mb-6&quot;]/nav[1]/ul[@class=&quot;text-sm font-medium leading-relaxed text-green-100 mr-15 to-md:hidden md:text-md&quot;]/li[@class=&quot;my-24 md:my-3&quot;]/ul[@class=&quot;test&quot;]/li[@class=&quot;text-black border-l-4 border-clear font-normal pl-6 my-24 leading-normal md:my-8 border-green-100 font-semibold&quot;]/a[1]</value>
      <webElementGuid>4860d911-8557-44ad-905f-a16b6f176928</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/section/div/div/div/nav/ul/li/ul/li/a</value>
      <webElementGuid>66198afd-82e4-4a35-a93b-ca77a8d72de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'訂貨')])[2]</value>
      <webElementGuid>7fe6b1f9-5de8-40b0-a870-95addd18582d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='顧客服務相關訊息'])[1]/following::a[1]</value>
      <webElementGuid>e3e23ee8-0cc8-41f7-81db-dcf1a3f2ce01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='常見問與答'])[4]/following::a[2]</value>
      <webElementGuid>eff668b1-eb2d-4eed-939c-7b82d3129e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='退換貨說明'])[2]/preceding::a[1]</value>
      <webElementGuid>43418998-6a4b-450d-bbf2-c898177e6e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='物流與運費'])[2]/preceding::a[2]</value>
      <webElementGuid>e6d51472-dd20-4dd3-b8de-14e9d2342b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://productstore2-uattw.melaleuca.com/help-center/faq/customer-service/orders')])[3]</value>
      <webElementGuid>ce3913fc-2f99-46bc-8b45-e99df0ca6c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>d8ad742f-5127-4589-bba1-8be350c344de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://productstore2-uattw.melaleuca.com/help-center/faq/customer-service/orders' and (text() = '訂貨' or . = '訂貨')]</value>
      <webElementGuid>0fd4f494-fd2c-4ec9-8d9b-afaa9ae8865c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
