<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_faq</name>
   <tag></tag>
   <elementGuidId>dece2f1c-ff4c-49e6-a15c-1d3f3e19ecab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/footer/div[2]/div[2]/nav/div[3]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4adbffe6-294a-402f-9b6f-cebb2c469b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/help-center/faq/customer-service/orders</value>
      <webElementGuid>3cf9d660-b24d-4a6d-871f-988c006fb887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-siteFooter__link</value>
      <webElementGuid>88893b24-7fca-4c8c-8740-be4c8c79fd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>常見問與答</value>
      <webElementGuid>874fd005-b8bd-427c-835a-ac9583c43ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer&quot;)/div[@class=&quot;o-siteFooter__section -content&quot;]/div[@class=&quot;o-siteFooter__row -content -signedIn&quot;]/nav[@class=&quot;o-siteFooter__col -nav&quot;]/div[@class=&quot;o-siteFooter__nav -right&quot;]/div[@class=&quot;o-siteFooter__navList&quot;]/ul[1]/li[@class=&quot;o-siteFooter__item&quot;]/a[@class=&quot;o-siteFooter__link&quot;]</value>
      <webElementGuid>e4a69f8d-fc8f-407b-8270-9d83a825feb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footer']/div[2]/div[2]/nav/div[2]/div[2]/ul/li[3]/a</value>
      <webElementGuid>be60f0b4-e0b6-466c-9453-aa44bdb0b51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'常見問與答')]</value>
      <webElementGuid>b6d39291-1867-40fa-9bb7-17836b9f5267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='聯絡美樂家'])[4]/following::a[1]</value>
      <webElementGuid>9e0e5423-1fdb-4665-b234-942c23e9ce25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='事業中心'])[3]/following::a[2]</value>
      <webElementGuid>e9c41c37-f72d-4bea-b728-8b85e7b648c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='公告事項'])[1]/preceding::a[1]</value>
      <webElementGuid>f743b93a-4023-44fe-a9c9-95e72529767c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tooltip:'])[1]/preceding::a[5]</value>
      <webElementGuid>754ac8b1-8e67-4fd3-8c9d-d352b87c7fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='常見問與答']/parent::*</value>
      <webElementGuid>6a569dde-e501-4f77-82fd-ff500e7a79db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/help-center/faq/customer-service/orders')]</value>
      <webElementGuid>25a24f35-42ce-4110-b1f9-0179857d9214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/ul/li[3]/a</value>
      <webElementGuid>9d703949-2567-4f93-bbca-d41898e6349f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/help-center/faq/customer-service/orders' and (text() = '常見問與答' or . = '常見問與答')]</value>
      <webElementGuid>9bcf922b-e883-42ed-a498-87323c096d38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
