<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_faq_bd_change</name>
   <tag></tag>
   <elementGuidId>dd5847f9-b4b2-483e-8e40-0e530b18ce62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/section/div/div/div/nav/ul/li[3]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>886db618-03cb-45da-837f-ced16483212c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://productstore2-uattw.melaleuca.com/help-center/faq/business-development/changes-in-your-business</value>
      <webElementGuid>f353d4ae-5d5d-4a32-9a4d-b21f9e43ece6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>事業相關變動</value>
      <webElementGuid>38082485-f9b8-4c85-9f38-0a1ac3fdf7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/section[@class=&quot;md:py-40&quot;]/div[@class=&quot;w-full px-10 pt-10 pb-36 mx-auto mt-10 mb-0 bg-white border max-w-contain border-gray-50 text-gray-150 md:mb-40 md:px-40 md:rounded&quot;]/div[@class=&quot;md:flex md:justify-between&quot;]/div[@class=&quot;mb-30 md:mb-6&quot;]/nav[1]/ul[@class=&quot;text-sm font-medium leading-relaxed text-green-100 mr-15 to-md:hidden md:text-md&quot;]/li[@class=&quot;my-24 md:my-3&quot;]/ul[@class=&quot;test&quot;]/li[@class=&quot;text-black border-l-4 border-clear font-normal pl-6 my-24 leading-normal md:my-8&quot;]/a[1]</value>
      <webElementGuid>a23e0e33-0e73-4e2c-9ee6-d2c452ff286d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/section/div/div/div/nav/ul/li[3]/ul/li[4]/a</value>
      <webElementGuid>e7a074cb-4352-4b99-9b8d-ef717b498b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'事業相關變動')])[2]</value>
      <webElementGuid>de073b8e-daac-489d-ad60-a9d5b04bd432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='經營自己的事業'])[4]/following::a[1]</value>
      <webElementGuid>2761594b-7ec9-4249-95bd-459d0f57f4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='推薦會員入會'])[2]/following::a[2]</value>
      <webElementGuid>66425372-23a8-49f8-8e7c-2b46ca43cc27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表＆工具'])[2]/preceding::a[1]</value>
      <webElementGuid>02ddea7b-fce1-4604-9cd6-a2e76ebe12b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='會議＆活動'])[2]/preceding::a[2]</value>
      <webElementGuid>54309fff-bec4-4cf8-a6eb-ee6c3ed82f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://productstore2-uattw.melaleuca.com/help-center/faq/business-development/changes-in-your-business')])[2]</value>
      <webElementGuid>452bb84f-850c-4dc5-8e14-8de263778c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[4]/a</value>
      <webElementGuid>048c4d6a-dff1-4016-9702-82c3c6906084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://productstore2-uattw.melaleuca.com/help-center/faq/business-development/changes-in-your-business' and (text() = '事業相關變動' or . = '事業相關變動')]</value>
      <webElementGuid>f3e5e460-4fa2-4e51-b978-491a16755147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
