<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_faq_bd_change_7</name>
   <tag></tag>
   <elementGuidId>eb9cf760-b6e0-4294-95e8-0209d3df410b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ID_{C02BF22F-ACC8-49AC-914A-9ED1E2931920}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f8e92fbf-1c47-4823-9a53-137d44f49f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ID_{C02BF22F-ACC8-49AC-914A-9ED1E2931920}</value>
      <webElementGuid>7fe9e340-c90e-4396-9b90-b43ac816a90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>SID_{C02BF22F-ACC8-49AC-914A-9ED1E2931920}</value>
      <webElementGuid>bb253cba-9ded-4a86-a64c-fd2430e45ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dee757e7-cc8c-4493-9e43-9132b43af34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-accordion__toggler</value>
      <webElementGuid>bb9defe9-4291-4d77-b486-f427340a41b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
組織內的事業代表暫停優惠顧客資格，他是否還要繼續購物?
</value>
      <webElementGuid>cc089cff-f356-4007-b6ec-23658d4fa88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ID_{C02BF22F-ACC8-49AC-914A-9ED1E2931920}&quot;)</value>
      <webElementGuid>880c3c15-bc0d-423e-961b-48a7da711ed5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ID_{C02BF22F-ACC8-49AC-914A-9ED1E2931920}']</value>
      <webElementGuid>4bc54aef-7e6b-4b3d-b6b4-54696ec4ff1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/section/div/div/div[2]/div[7]/h2/button</value>
      <webElementGuid>d399de6f-9500-4f8d-adaf-f598dca4d49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='如果有會員連續二個月未活動，但又訂購了35點以上的產品，那會如何?'])[1]/following::button[1]</value>
      <webElementGuid>ff6e329b-13ab-49fb-894e-4730076cebcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我組織的一位事業代表在過去二個月都未達業績標準，有任何方法能避免他失去事業組織嗎?'])[1]/following::button[2]</value>
      <webElementGuid>37651b5b-0934-4322-904a-9b82f7434f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='美樂家事業是否可繼承給他人?'])[1]/preceding::button[1]</value>
      <webElementGuid>fefbcf7b-2eb1-442d-b8f9-c917c2238598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全新網站使用體驗問卷'])[1]/preceding::button[2]</value>
      <webElementGuid>c692a2c4-ebca-4d09-9801-4209188ead80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='組織內的事業代表暫停優惠顧客資格，他是否還要繼續購物?']/parent::*</value>
      <webElementGuid>1d9de9a8-cb2c-4c8b-bd49-9fbc7f8f48cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/h2/button</value>
      <webElementGuid>cd2612de-9440-462c-ad92-5b27ce16dcfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ID_{C02BF22F-ACC8-49AC-914A-9ED1E2931920}' and (text() = '
組織內的事業代表暫停優惠顧客資格，他是否還要繼續購物?
' or . = '
組織內的事業代表暫停優惠顧客資格，他是否還要繼續購物?
')]</value>
      <webElementGuid>b2ed7561-cef2-4825-ab10-644dde85f71e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
