<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_faq_bd_change_4</name>
   <tag></tag>
   <elementGuidId>efa94ece-9882-458b-92be-b7f0ee5e3aa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ID_{5597F760-DDC8-4360-86E9-6470AECAF18E}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af8ca4dd-3ddd-468e-90d5-611406b7682f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ID_{5597F760-DDC8-4360-86E9-6470AECAF18E}</value>
      <webElementGuid>e066085b-6355-42f2-a467-57191a6224f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>SID_{5597F760-DDC8-4360-86E9-6470AECAF18E}</value>
      <webElementGuid>297aa507-2eb8-4f5d-8b4c-892137fef344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2978b710-b98d-4868-86b3-e08af9829ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-accordion__toggler</value>
      <webElementGuid>0b2b02c4-ed06-4c12-a4a9-6ee640bf0f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
如果組織內有未達業績標準的會員，我的組織結構會如何?
</value>
      <webElementGuid>2d49733f-9ffd-430a-ab87-d6619990c9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ID_{5597F760-DDC8-4360-86E9-6470AECAF18E}&quot;)</value>
      <webElementGuid>94029238-bcad-44ba-ad8c-1076542b80c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ID_{5597F760-DDC8-4360-86E9-6470AECAF18E}']</value>
      <webElementGuid>67b8ecf6-cc92-46b3-a367-eceeed30df4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/section/div/div/div[2]/div[4]/h2/button</value>
      <webElementGuid>fe86514e-e9de-4f9d-9988-2d67a4237876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='會員入會當月是否可變更輔導事業代表?'])[1]/following::button[1]</value>
      <webElementGuid>1ad44c89-593a-435f-9629-0e9802fab73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我能否申請變更組織夥伴的輔導事業代表?'])[1]/following::button[2]</value>
      <webElementGuid>3848ba13-345f-4d6d-88b2-5e2df6b034c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我組織的一位事業代表在過去二個月都未達業績標準，有任何方法能避免他失去事業組織嗎?'])[1]/preceding::button[1]</value>
      <webElementGuid>003c401a-687f-4e21-98a0-fe34527eb4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='如果有會員連續二個月未活動，但又訂購了35點以上的產品，那會如何?'])[1]/preceding::button[2]</value>
      <webElementGuid>516b09c5-68af-4f71-b165-0c05d63fd4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='如果組織內有未達業績標準的會員，我的組織結構會如何?']/parent::*</value>
      <webElementGuid>7dcb2e57-a33d-4237-8024-0492b53e31eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/h2/button</value>
      <webElementGuid>b998286e-8bf7-4c80-949f-fc3505222dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ID_{5597F760-DDC8-4360-86E9-6470AECAF18E}' and (text() = '
如果組織內有未達業績標準的會員，我的組織結構會如何?
' or . = '
如果組織內有未達業績標準的會員，我的組織結構會如何?
')]</value>
      <webElementGuid>0d2ba92a-6f7a-4c5f-bb5f-4a2a4af08090</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
