<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_faq_cs_orders_a</name>
   <tag></tag>
   <elementGuidId>73f432e4-67c0-4713-962f-b5d2b635acf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ID_{6A5CD278-1561-4F92-A8C2-AA8080F51C8F}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fff2c431-0f99-4986-82f1-2e1756fa8b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ID_{6A5CD278-1561-4F92-A8C2-AA8080F51C8F}</value>
      <webElementGuid>51cce82a-f505-4447-ab27-12ce68db85e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>SID_{6A5CD278-1561-4F92-A8C2-AA8080F51C8F}</value>
      <webElementGuid>95464735-799a-405b-9661-0d271f596b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>27e77698-ee8b-420b-9492-7dfdec25fa04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-accordion__toggler</value>
      <webElementGuid>f48e5a12-f5f8-42a8-8ea0-c9afbeab1e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
網路可以查詢歷史訂單嗎?
</value>
      <webElementGuid>59a158f0-a1a6-4d37-b0b8-3ed7f91e47a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ID_{6A5CD278-1561-4F92-A8C2-AA8080F51C8F}&quot;)</value>
      <webElementGuid>292586f0-6885-4f30-930e-a6986eb9cc8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ID_{6A5CD278-1561-4F92-A8C2-AA8080F51C8F}']</value>
      <webElementGuid>62750a9b-66e1-4b55-b181-7609839dfd95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/section/div/div/div[2]/div[10]/h2/button</value>
      <webElementGuid>d474f1ac-4fc5-4083-bf10-63f14e8ca14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='訂單記錄'])[2]/following::button[1]</value>
      <webElementGuid>7f07dd48-5332-45bf-8b4b-eaa254e3d770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='如何查看我的訂貨狀態?'])[1]/following::button[1]</value>
      <webElementGuid>ca2fcd7c-e0fb-4607-99d8-9feaa94b86dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='訂單記錄'])[3]/preceding::button[1]</value>
      <webElementGuid>b0814a86-c9c7-4dc8-bc0c-7bd068cedf64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='如何變更或取消已下的網路訂單?'])[1]/preceding::button[1]</value>
      <webElementGuid>3739bb1e-80c5-48e8-8fcf-488aa67dda01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='網路可以查詢歷史訂單嗎?']/parent::*</value>
      <webElementGuid>8d06c3da-7e70-4353-9b3f-82c2098cc87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/h2/button</value>
      <webElementGuid>b792e3f6-2c79-4a1f-8edf-dd126cadf565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ID_{6A5CD278-1561-4F92-A8C2-AA8080F51C8F}' and (text() = '
網路可以查詢歷史訂單嗎?
' or . = '
網路可以查詢歷史訂單嗎?
')]</value>
      <webElementGuid>f556aa8f-5a32-4080-b4bd-afb3286fdb36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
