<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_faq_cs_orders_d</name>
   <tag></tag>
   <elementGuidId>51903c19-ee5c-4e60-be9d-e4655c93fa8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ID_{79137DB7-A4BB-4670-9974-89FB464279B1}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1aaa15b5-7146-473a-8e96-91cb24adcbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ID_{79137DB7-A4BB-4670-9974-89FB464279B1}</value>
      <webElementGuid>b46edd00-2c5a-43d8-8a2f-cc18e72b9ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>SID_{79137DB7-A4BB-4670-9974-89FB464279B1}</value>
      <webElementGuid>4a68cd45-1031-458f-bba6-6f28d78673f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>89af259d-a846-4d1c-8075-c8102a14d90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-accordion__toggler</value>
      <webElementGuid>55560365-e88d-4559-aa55-fe0c46f71877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
何謂預備訂單服務?
</value>
      <webElementGuid>1304a183-2af1-419d-9ba9-c103eca35e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ID_{79137DB7-A4BB-4670-9974-89FB464279B1}&quot;)</value>
      <webElementGuid>6dd60920-3633-44fa-a89c-b991ee4ce52a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ID_{79137DB7-A4BB-4670-9974-89FB464279B1}']</value>
      <webElementGuid>9d9beecc-e8ef-449e-aebf-9b850545569b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/section/div/div/div[2]/div[13]/h2/button</value>
      <webElementGuid>19c7d55b-b76f-404c-b1e8-cf0a3b19ba9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='如果忘了購物怎麼辦呢?'])[1]/following::button[1]</value>
      <webElementGuid>b4420e13-fcf1-408e-b2fa-5d45052ddf10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='如何變更或取消已下的網路訂單?'])[1]/following::button[2]</value>
      <webElementGuid>25abafa8-1820-48b6-b018-3a8e8a6ae11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='編輯您的預備訂單'])[1]/preceding::button[1]</value>
      <webElementGuid>67b3b123-604a-4295-8eaf-cd7adb8f2fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='如何變更預備訂單的內容?'])[1]/preceding::button[1]</value>
      <webElementGuid>ed2703b4-6528-4b06-9f08-3632476af3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='何謂預備訂單服務?']/parent::*</value>
      <webElementGuid>e2f767cb-1e45-4158-9ae9-82dd7a9ce1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/h2/button</value>
      <webElementGuid>0528b264-0c82-422e-91d2-0950a3773b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ID_{79137DB7-A4BB-4670-9974-89FB464279B1}' and (text() = '
何謂預備訂單服務?
' or . = '
何謂預備訂單服務?
')]</value>
      <webElementGuid>531c8031-e23f-417f-beb6-6ca7b32f229d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
