<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_faq_cs_invoice_9</name>
   <tag></tag>
   <elementGuidId>f395dae3-c350-4a6b-b9b6-35820c53628c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ID_{8DC4BE6E-FCBE-403E-8E9E-382DB66A5537}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>94a7464b-c032-4d29-8255-793029a67c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ID_{8DC4BE6E-FCBE-403E-8E9E-382DB66A5537}</value>
      <webElementGuid>839d132d-92be-498c-a4e2-3f3967ae67bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>SID_{8DC4BE6E-FCBE-403E-8E9E-382DB66A5537}</value>
      <webElementGuid>2b6ca600-0f94-451a-8840-6f2c26c00215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aacd865d-d07a-438e-b1cf-2a0a8f751189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-accordion__toggler</value>
      <webElementGuid>c59a6732-a48b-4bd6-8bb3-edb047c90d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
發票如果捐贈後，是否就不能進行退換貨了呢?
</value>
      <webElementGuid>78cc8ede-2aa8-4bf9-a9e1-fa84bfde7681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ID_{8DC4BE6E-FCBE-403E-8E9E-382DB66A5537}&quot;)</value>
      <webElementGuid>9a33516f-ebb8-418d-95dd-a40a7b54837d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ID_{8DC4BE6E-FCBE-403E-8E9E-382DB66A5537}']</value>
      <webElementGuid>99122ce2-ed0e-49bb-8293-13fea5602529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/section/div/div/div[2]/div[9]/h2/button</value>
      <webElementGuid>8f74d917-702d-4358-81e9-07065f6046a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='中獎後的兌領獎程序有無改變?'])[1]/following::button[1]</value>
      <webElementGuid>1c6b5ae5-ed91-4485-a169-3da28b7a6100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='美樂家開立之電子發票如果收到公司通知中獎了，該如何領獎?'])[1]/following::button[2]</value>
      <webElementGuid>6d667d4d-1c89-4bd7-b80b-8634179d9c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='在美樂家消費之發票號碼，是否可以查詢到?'])[1]/preceding::button[1]</value>
      <webElementGuid>8dbd6032-921d-489b-a146-c6f7f2caab1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我收到預備訂單，為什麼沒有發票?'])[1]/preceding::button[2]</value>
      <webElementGuid>c8aca83b-e99a-4ed1-9ffa-bccc87d66e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='發票如果捐贈後，是否就不能進行退換貨了呢?']/parent::*</value>
      <webElementGuid>22430f0f-0111-4f80-b9e3-58c234acaa10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/h2/button</value>
      <webElementGuid>58cb6529-3ca3-4fc3-8399-cdeb089cd34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ID_{8DC4BE6E-FCBE-403E-8E9E-382DB66A5537}' and (text() = '
發票如果捐贈後，是否就不能進行退換貨了呢?
' or . = '
發票如果捐贈後，是否就不能進行退換貨了呢?
')]</value>
      <webElementGuid>68359a9f-0e82-415d-b69f-1677e05694eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
