<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_faq_bd_change_2</name>
   <tag></tag>
   <elementGuidId>dc45417c-07dc-422a-84d5-68ca0aafc934</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ID_{22329CA8-32A5-47FE-BD86-BCA88DB4F7E2}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e90124b-580a-47b1-a61c-b3e1458a2f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ID_{22329CA8-32A5-47FE-BD86-BCA88DB4F7E2}</value>
      <webElementGuid>2e59748e-3f70-4c29-ae5f-51fe9a97d326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>SID_{22329CA8-32A5-47FE-BD86-BCA88DB4F7E2}</value>
      <webElementGuid>b5b5be68-6c28-4e72-a97a-20f41fc7e696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b14c0256-4d57-4a7a-9d2a-b76226d1a8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-accordion__toggler</value>
      <webElementGuid>b1ebd920-cb3f-4b64-8368-120fc4ef514a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
我能否申請變更組織夥伴的輔導事業代表?
</value>
      <webElementGuid>1c8c459a-22a3-4f4a-811f-7036a53c6e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ID_{22329CA8-32A5-47FE-BD86-BCA88DB4F7E2}&quot;)</value>
      <webElementGuid>8f4ec8f3-1c3c-4f04-bfb7-0ba40a3296fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ID_{22329CA8-32A5-47FE-BD86-BCA88DB4F7E2}']</value>
      <webElementGuid>ece2c462-932b-4e6b-85cb-3d84332a002a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/section/div/div/div[2]/div[2]/h2/button</value>
      <webElementGuid>af2bfb67-1735-4416-9719-9b0d44ee120d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='如何申請更改會員基本資料？'])[1]/following::button[1]</value>
      <webElementGuid>60e73203-d114-4c99-9007-d361fb0dd5e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='事業相關變動'])[5]/following::button[2]</value>
      <webElementGuid>01cbcdfe-a1cb-41fd-b7ff-e277186b2b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='會員入會當月是否可變更輔導事業代表?'])[1]/preceding::button[1]</value>
      <webElementGuid>31593708-5711-465f-9395-853708c9eb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='如果組織內有未達業績標準的會員，我的組織結構會如何?'])[1]/preceding::button[2]</value>
      <webElementGuid>79a97fea-b2bd-469d-b63d-5fbb512d6b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='我能否申請變更組織夥伴的輔導事業代表?']/parent::*</value>
      <webElementGuid>411f2406-5eaa-4ca7-9870-770efaf51fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h2/button</value>
      <webElementGuid>95413e92-b2c4-4058-90a3-6ca8b2c3c63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ID_{22329CA8-32A5-47FE-BD86-BCA88DB4F7E2}' and (text() = '
我能否申請變更組織夥伴的輔導事業代表?
' or . = '
我能否申請變更組織夥伴的輔導事業代表?
')]</value>
      <webElementGuid>cfa5a049-8599-448d-874d-a48d95a9cb6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
