<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_faq_cs_orders_4</name>
   <tag></tag>
   <elementGuidId>b7fcb3f0-f4e8-4751-bb88-5a1b003ea3ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ID_{8730F120-2413-4548-A741-F29BE7BDAD79}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52da98a9-859a-4c9d-98b9-fc90c7b5c597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ID_{8730F120-2413-4548-A741-F29BE7BDAD79}</value>
      <webElementGuid>3fccdcc0-136f-4cbe-a22c-27c42b6f574b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>SID_{8730F120-2413-4548-A741-F29BE7BDAD79}</value>
      <webElementGuid>8bf50991-7eb1-4691-b095-f4713e3e458c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4067d8a2-b17e-4757-9215-72f644b316f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-accordion__toggler</value>
      <webElementGuid>ec77caa9-5a1e-49ee-b543-c4aeb07bf7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
如何變更網路密碼與變更電子郵件信箱?
</value>
      <webElementGuid>158eeee3-e2fa-4084-b512-c608c46de0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ID_{8730F120-2413-4548-A741-F29BE7BDAD79}&quot;)</value>
      <webElementGuid>c4f2398b-0ef4-4392-a3f8-9ab16d55f5b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ID_{8730F120-2413-4548-A741-F29BE7BDAD79}']</value>
      <webElementGuid>97fe22a3-648d-42cb-af9f-0f2af970f57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/section/div/div/div[2]/div[4]/h2/button</value>
      <webElementGuid>699cddc9-1f14-4be7-b2ec-3ce9a316f59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我的帳戶'])[4]/following::button[1]</value>
      <webElementGuid>732beee6-98da-491c-94ab-47d363cfbcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我如何取得我的會員編號？'])[1]/following::button[1]</value>
      <webElementGuid>d9b17a0e-256b-4ae9-9431-77c91529b957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='帳戶設定'])[3]/preceding::button[1]</value>
      <webElementGuid>9fdeca51-e9a2-4dd1-b9de-66f7294d2a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='每月訂貨的截止日期?'])[1]/preceding::button[1]</value>
      <webElementGuid>b9124f02-54cf-4e11-ac21-2702a8675410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='如何變更網路密碼與變更電子郵件信箱?']/parent::*</value>
      <webElementGuid>81334bae-23b2-47e6-92fc-ea1ca6220036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/h2/button</value>
      <webElementGuid>2a142011-27d1-4b5c-bf19-f1f586cb6d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ID_{8730F120-2413-4548-A741-F29BE7BDAD79}' and (text() = '
如何變更網路密碼與變更電子郵件信箱?
' or . = '
如何變更網路密碼與變更電子郵件信箱?
')]</value>
      <webElementGuid>7d2e436b-e0e3-4a01-90a3-2cde774e022d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
