<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BusinessCenter_OLE_Invitation_save</name>
   <tag></tag>
   <elementGuidId>0eee2e2f-424d-4095-963d-2d41d10e98dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnUpdateContact']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnUpdateContact</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8beb512f-b3da-407b-b137-288c47d7db74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnUpdateContact</value>
      <webElementGuid>3ea79643-bd37-40cd-a305-f7eaad5e7824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button pure-button-green ng-scope ng-binding</value>
      <webElementGuid>9ad4514c-88d8-4ae3-a988-bacc2000fa4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>contact.FirstName.length > 0 &amp;&amp; (contact.EmailAddress.length > 0 || contact.PhoneNumber.length > 0)</value>
      <webElementGuid>a01838e2-1de9-4de3-9aa3-7e9e7ea9e83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>isValidPhone &amp;&amp; !isValidInvitePhone &amp;&amp; updateContactInformation(contact.CustomerContactId)</value>
      <webElementGuid>26226524-bdcf-4725-a1e8-b126067f8728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>儲存</value>
      <webElementGuid>31932367-0d08-4d00-8d23-26a8dee13888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnUpdateContact&quot;)</value>
      <webElementGuid>03bf0234-270b-45b3-bed8-7376ca4b420a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btnUpdateContact']</value>
      <webElementGuid>c3730e64-8127-40e9-8d8d-06fbdebddfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvEditContactInfo']/div/div[4]/div[7]/div[2]</value>
      <webElementGuid>3ea39201-2d1a-4516-a59e-2b0453772585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='取消'])[2]/following::div[1]</value>
      <webElementGuid>04287c8b-f661-41ab-a55d-1d54b35798c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='地區'])[2]/following::div[5]</value>
      <webElementGuid>ac01ccde-1a2c-4e24-b01f-c3fe4101ad89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='發送!'])[1]/preceding::div[2]</value>
      <webElementGuid>6cd93218-9f03-49e3-88f9-8cb2d4e3e119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='儲存']/parent::*</value>
      <webElementGuid>21d49cd9-8c8f-4b91-8e03-43e16483f18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/div[7]/div[2]</value>
      <webElementGuid>9f47e93f-e7e0-41b9-ab0e-2de23d1598f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
