<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_offsale</name>
   <tag></tag>
   <elementGuidId>d386a4f8-a0ee-4b65-8197-81edb2c9f291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_itemOffSale']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pdp_itemOffSale</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>26e4467e-6f92-4ea6-9ac1-58e9ea9bd8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pdp_itemOffSale</value>
      <webElementGuid>07ea5604-36f2-4513-a753-65df85ef9a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>暫時缺貨</value>
      <webElementGuid>3b5a3e2b-aca4-4bd0-a6c6-053072e72d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_itemOffSale&quot;)</value>
      <webElementGuid>193d6fe4-4a2c-4f98-a2fd-43f1324f7bfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pdp_itemOffSale']</value>
      <webElementGuid>0d450420-c4d4-4724-810e-1734a369a973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_productConfigureSection']/div[2]</value>
      <webElementGuid>c114f835-135c-4ea8-bd38-c9e0f78a6dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='暫時缺貨'])[1]/following::div[2]</value>
      <webElementGuid>7c664c44-561c-46d9-8642-672e767fddea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新增至購物車'])[1]/following::div[4]</value>
      <webElementGuid>376c89a1-9bcc-440f-bd80-a228a27643ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='暫時缺貨'])[3]/preceding::div[1]</value>
      <webElementGuid>573e3f39-0a54-4770-b965-6b65d0113407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='增加至我的清單'])[1]/preceding::div[3]</value>
      <webElementGuid>1892ad03-d951-4a93-8e3d-ece609b9599a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]</value>
      <webElementGuid>d2f26fa0-4356-4f19-8048-60f6c20bea6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pdp_itemOffSale' and (text() = '暫時缺貨' or . = '暫時缺貨')]</value>
      <webElementGuid>6381ece7-f10a-44a1-8dc3-4146cb1d8a1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
