<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BackDatingDuration_cancel</name>
   <tag></tag>
   <elementGuidId>22f8124a-9720-48a6-813c-42fd8fd2654e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_ctrlBackDates_ctl00_lnkDelete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/table/tbody/tr[2]/td[2]/div/div/div[1]/table[2]/tbody/tr[3]/td[6]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29496a6f-caeb-4a8d-9491-04dc87ea6bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>3243d549-5382-48f0-b78e-07947166094d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ctrlBackDates$ctl00$lnkDelete</value>
      <webElementGuid>07bbb73b-5656-4362-9257-da5d73f11551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_ctrlBackDates_ctl00_lnkDelete</value>
      <webElementGuid>787750e8-78c0-48dd-a2e3-527b71919e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>cf618a35-56ee-4fa0-bcf2-34d1e9c47a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Images/remove.png</value>
      <webElementGuid>daebfc2f-a7dc-493b-b504-1e4b2926fc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Are you sure you want to delete this item?');</value>
      <webElementGuid>4535e1b8-1e2b-479d-b52b-046b43ddefd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_ctrlBackDates_ctl00_lnkDelete&quot;)</value>
      <webElementGuid>c17f7b0f-b96d-44fc-98ef-7527065a2471</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_ctrlBackDates_ctl00_lnkDelete']</value>
      <webElementGuid>5935f4e1-c9fd-46b9-bbff-81ba24bee8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/table/tbody/tr[2]/td[2]/div/div/div/table[2]/tbody/tr[3]/td[6]/input</value>
      <webElementGuid>b0706d96-a79a-44c5-a620-f371233970a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>c3a7681e-f719-4215-b14f-a06fc8ab3970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$ctrlBackDates$ctl00$lnkDelete' and @id = 'ctl00_ContentPlaceHolder1_ctrlBackDates_ctl00_lnkDelete' and @title = 'Delete' and @src = 'Images/remove.png']</value>
      <webElementGuid>bfcf2fca-3f91-4803-b6ba-df62af9cd3cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
