<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_BusinessCenter_tw_ReportandTool_ReportandTool_view_enable_hk</name>
   <tag></tag>
   <elementGuidId>6f6f706e-ee92-4903-a1dc-665437ef7253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl01_btn']/span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '立即啟用' or . = '立即啟用')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.btnTxt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c564219b-2761-4e3c-ad19-9d86981b8517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnTxt</value>
      <webElementGuid>5b116ff1-37f2-42d6-b295-8f97fe2a7f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>立即啟用</value>
      <webElementGuid>02fc2576-9659-4035-92ac-657446f46a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl01_btn&quot;)/span[@class=&quot;btnTxt&quot;]</value>
      <webElementGuid>93d7f149-9fb3-493a-8ac6-70e9545bba75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl01_btn']/span[2]</value>
      <webElementGuid>304a24d2-e746-4154-8020-485bf5e84751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='立即啟用'])[1]/following::span[2]</value>
      <webElementGuid>747a357d-5797-4ac2-b011-574e1af426cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='經營生動活潑，讓您瀏覽組織各個面向，如：警訊內容、關鍵績效指數、階銜＆目標…等！'])[1]/following::span[3]</value>
      <webElementGuid>70529a1a-ad7f-46ac-bed5-d237a719ec1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='一旦勾選即視為同意及接受下載注意事項'])[1]/preceding::span[3]</value>
      <webElementGuid>e3160974-0d5f-4be9-b1f3-84c6ef3a93ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='關閉'])[19]/preceding::span[4]</value>
      <webElementGuid>4d5f059c-8f08-4a7f-9fbd-904e7a60ab2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span[2]</value>
      <webElementGuid>cf8243b0-0427-4fd6-ae22-e8622b9ff251</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
