<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_HK_HSBC Banking</name>
   <tag></tag>
   <elementGuidId>15de1c50-8243-4493-85fe-58a11c83efcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'select2-BasePaymethodViewModel_AvailableBankNames-container' and @title = '004 香港上海滙豐銀行有限公司The Hongkong and Shanghai Banking Corporation Ltd' and (text() = '004 香港上海滙豐銀行有限公司The Hongkong and Shanghai Banking Corporation Ltd' or . = '004 香港上海滙豐銀行有限公司The Hongkong and Shanghai Banking Corporation Ltd')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;BasePaymethodViewModel_AvailableBankNames&quot;]/option[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-BasePaymethodViewModel_AvailableBankNames-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a2a11c99-87df-4a52-92d1-daafb8b6c92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>f3d4e2bb-102b-46b1-b66c-f0395041b37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-BasePaymethodViewModel_AvailableBankNames-container</value>
      <webElementGuid>68da5bbc-a2e6-43e2-83df-2100bf71fbfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>8715ceb6-bda8-488e-a219-0fea2d0ed190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1daab6d1-48a3-44fc-ba81-ac8e5e021497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>004 香港上海滙豐銀行有限公司The Hongkong and Shanghai Banking Corporation Ltd</value>
      <webElementGuid>7365f86c-fb0f-4d86-a506-b7785c8cfe27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>004 香港上海滙豐銀行有限公司The Hongkong and Shanghai Banking Corporation Ltd</value>
      <webElementGuid>4e5607c1-70f6-4783-bd1a-8be45c1a232b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-BasePaymethodViewModel_AvailableBankNames-container&quot;)</value>
      <webElementGuid>2d92d282-2089-41e1-892b-41e67e5715d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-BasePaymethodViewModel_AvailableBankNames-container']</value>
      <webElementGuid>5470b8a0-d92d-4da1-904a-9ae9561ffd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='availableBankNames']/span/span/span/span</value>
      <webElementGuid>7c2ba882-4004-4454-9906-effac6799fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='銀行名稱*'])[1]/following::span[4]</value>
      <webElementGuid>e587d549-de1f-4722-9b9b-705787e088f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='帳戶持有人姓名*'])[1]/following::span[4]</value>
      <webElementGuid>20b51c26-f60b-4df2-a8f1-230134a78c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='帳戶號碼*'])[1]/preceding::span[3]</value>
      <webElementGuid>c6d9ed96-6a61-42c7-834f-3b00179dc1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='帳戶資料標題'])[1]/preceding::span[3]</value>
      <webElementGuid>c1188f7c-a2bd-4249-8c4c-1fa563e82b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>369b5c44-fcc9-4af9-9363-fbb56eae987a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
