<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ (6)</name>
   <tag></tag>
   <elementGuidId>a05c6579-1597-4158-b86d-ff7a7e673799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='simplePageContent']/div/div[2]/div/div/div[8]/div/div/ul/li[3]/div/div/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MyAccount_OtherOptions.myAccountLanding_Buttons > div.infoRight > div.tdInfoRight > ul > li.editButtonContainer > div.btn.blue24 > div > a > span.btnTxt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnTxt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>查看其他訊息</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simplePageContent&quot;)/div[@class=&quot;myAccountWrapper&quot;]/div[2]/div[@class=&quot;contentDisplay&quot;]/div[1]/div[@class=&quot;MyAccount_OtherOptions myAccountLanding_Buttons&quot;]/div[@class=&quot;infoRight&quot;]/div[@class=&quot;tdInfoRight&quot;]/ul[1]/li[@class=&quot;editButtonContainer&quot;]/div[@class=&quot;btn blue24&quot;]/div[1]/a[1]/span[@class=&quot;btnTxt&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='simplePageContent']/div/div[2]/div/div/div[8]/div/div/ul/li[3]/div/div/a/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查看其他訊息'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='會員權益訊息'])[1]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='會員資料'])[2]/preceding::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查看您的所有會員資料'])[1]/preceding::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/ul/li[3]/div/div/a/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
