<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OrgChangeResult1</name>
   <tag></tag>
   <elementGuidId>d1483e27-2617-443f-951f-1b18d3af2f88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_lblAfterPostbackError' and (text() = '您的移線成功' or . = '您的移線成功')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form[2]/div[8]/div[2]/div[2]/div/div[1]/div[1]/div/div[3]/div[2]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_lblAfterPostbackError</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0be4bfe-fb57-4364-9ef8-0b683d053ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_lblAfterPostbackError</value>
      <webElementGuid>0d84be65-a009-47af-ac07-fbef8e2c6615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>necValidateErrorMain</value>
      <webElementGuid>4e18f9f3-4951-4ff6-8c65-17a107e35adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>您的移線成功</value>
      <webElementGuid>8dde5a9c-c475-46c7-b1bd-2fad979f8a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_lblAfterPostbackError&quot;)</value>
      <webElementGuid>668ee2c8-b7f2-4dcb-98ad-3cfb195e2286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_lblAfterPostbackError']</value>
      <webElementGuid>982d6ee7-a6d7-40c2-af1e-29f6a1b33510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabContainer1']/div</value>
      <webElementGuid>48bff7a1-c173-4481-8b99-19ab051f5ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='組織轉換總覽'])[1]/following::div[3]</value>
      <webElementGuid>87f4be5f-1fe5-4f14-a8fd-6b11b5b7e9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='直屬...'])[1]/following::div[3]</value>
      <webElementGuid>0dacf842-4d8b-4aad-bcdb-f2764c0d4c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我想要：'])[1]/preceding::div[1]</value>
      <webElementGuid>5cf9d9e5-d150-43a9-a92d-bfc250025950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='變更輔導事業代表'])[1]/preceding::div[1]</value>
      <webElementGuid>2be1ba64-e8ae-48c5-84fa-86603f9fe2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='您的移線成功']/parent::*</value>
      <webElementGuid>fd9e0c93-4371-4abb-9fb8-06db3e0d39ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div</value>
      <webElementGuid>6e97af46-e457-47fd-b4cd-adebb39fdb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_lblAfterPostbackError' and (text() = '您的移線成功' or . = '您的移線成功')]</value>
      <webElementGuid>e838bd09-2eae-4209-aac9-c1a401782ae2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
