<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_applicant</name>
   <tag></tag>
   <elementGuidId>23e75fa9-78c6-4ed1-b914-e15f72c5c990</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_txtMovePhoneSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_txtMovePhoneSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>badd3141-1fc4-466a-94f2-3082dea02de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ContentPlaceHolderMain$ContentPlaceHolderMain$ctrlNec$txtMovePhoneSearch</value>
      <webElementGuid>c8a7fc22-660d-483f-97c0-20cb9826a1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e0d7a16-a90e-4128-abc3-a7810bb4c3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_txtMovePhoneSearch</value>
      <webElementGuid>727dd2d8-5800-4e80-ae95-1117dcd5dc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_txtMovePhoneSearch&quot;)</value>
      <webElementGuid>0146d6c7-aa9b-490f-999e-33bc8314c401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_txtMovePhoneSearch']</value>
      <webElementGuid>c4d9f1f0-34fe-4435-b306-651a1ba1360c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panelMove2']/div/div/input</value>
      <webElementGuid>94f31925-8355-4697-8877-6a57c168e7db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>d5b889ef-07e4-4aa9-bd8f-6cd44845b969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$ContentPlaceHolderMain$ContentPlaceHolderMain$ctrlNec$txtMovePhoneSearch' and @type = 'text' and @id = 'ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_txtMovePhoneSearch']</value>
      <webElementGuid>18daaf3d-2a46-4e34-a0a2-008604edc7a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
