<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OrgChange_Continue_2</name>
   <tag></tag>
   <elementGuidId>873f3ada-97e9-44f0-80a7-c1ef27cca5ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form[2]/div[8]/div[2]/div[2]/div/div[1]/div[1]/div/div[3]/div[2]/div[2]/div[1]/div[3]/div/div/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.btnTxt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f27079b3-2d35-4544-b6cd-3c457d897edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnTxt</value>
      <webElementGuid>7d6c0b22-e8a2-477f-bb24-96676edab5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>繼續</value>
      <webElementGuid>597e40f4-d0fd-47aa-9133-2580a4951d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_btnContinue1_btn&quot;)/span[@class=&quot;btnTxt&quot;]</value>
      <webElementGuid>188bb446-7068-4535-82fd-72652fbaf49a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ctl00_ContentPlaceHolderMain_ContentPlaceHolderMain_ctrlNec_btnContinue1_btn']/span[2]</value>
      <webElementGuid>5d586380-19d5-4331-bd8f-b1c53edb89fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='繼續'])[1]/following::span[2]</value>
      <webElementGuid>e6beccd8-1d58-4fcc-ba61-ffac6353e9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='變更輔導事業代表'])[1]/following::span[3]</value>
      <webElementGuid>bf760d43-0877-459a-bff4-e9e7291ceff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入會者電話號碼'])[1]/preceding::span[3]</value>
      <webElementGuid>b6d0ac72-c630-4fd7-887f-85bb7a29755d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span[2]</value>
      <webElementGuid>eb1845de-1a30-4dd6-bead-4bd13c940124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '繼續' or . = '繼續')]</value>
      <webElementGuid>cc467792-7444-4876-bf7b-edf01adb62e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
