<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_enroller_generation1</name>
   <tag></tag>
   <elementGuidId>95ec48f4-cd2a-4bf9-9242-6e573737652a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form[2]/div[8]/div[2]/div[2]/div/div[1]/div[1]/div/div[3]/div[3]/div[2]/table/tbody/tr/td[1]/div/div/div/div[1]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0dc4bace-92c4-48f4-9993-0050fd559878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>stanleytest9</value>
      <webElementGuid>4df87d69-86d1-4f61-928a-09f5e6cbe178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myOrg1&quot;)/div[@id=&quot;divRepeater&quot;]/span[2]</value>
      <webElementGuid>476ab8c1-fc93-4934-ac37-7e66fcfb9f36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divRepeater']/span[2]</value>
      <webElementGuid>ee923230-4d01-4c6c-bc5f-a709121f46ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='第一代:'])[1]/following::span[2]</value>
      <webElementGuid>b27f73b0-ffce-46df-87ce-f186d5114e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='賺大錢 or YYY'])[1]/preceding::span[2]</value>
      <webElementGuid>14b2229e-34d0-496a-908d-09ad3e21a446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='陳盼七二'])[1]/preceding::span[4]</value>
      <webElementGuid>54fa2a7e-80d9-44ef-9db4-dec22d83ea7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='stanleytest9']/parent::*</value>
      <webElementGuid>f97faa2d-7c85-4def-b1fe-02770fd71d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/span[2]</value>
      <webElementGuid>7991c823-7ba0-425d-af30-bb12a9d14b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'stanleytest9' or . = 'stanleytest9')]</value>
      <webElementGuid>428d5ec3-72c5-48bf-a2b3-2eee78e3a543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
