<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ (3)</name>
   <tag></tag>
   <elementGuidId>0a99d6d9-cb7a-4ad0-a14f-76955d7e0ab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.pure-menu-item.ng-scope > a.pure-menu-link.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'會員顧客協議書')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>346659cd-f051-466e-9fce-74e69dc345b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/enrollmentPage/</value>
      <webElementGuid>88a83586-2a46-4b09-b371-3b06f7e650cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pure-menu-link ng-binding</value>
      <webElementGuid>3f322665-61d9-4adf-9ee2-e90e1b6f948d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>會員顧客協議書</value>
      <webElementGuid>b1988516-3512-4445-a52d-5f7877c67239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope&quot;]/header[1]/div[@class=&quot;menu-container pure-menu pure-menu-horizontal&quot;]/ul[@class=&quot;pure-menu-list&quot;]/li[@class=&quot;pure-menu-item pure-menu-has-children pure-menu-allow-hover&quot;]/ul[@class=&quot;pure-menu-children&quot;]/li[@class=&quot;pure-menu-item ng-scope&quot;]/a[@class=&quot;pure-menu-link ng-binding&quot;]</value>
      <webElementGuid>8293c738-d6d1-4b01-a606-c95af2951d65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'會員顧客協議書')]</value>
      <webElementGuid>04d19cca-7542-43a3-a168-09d077a2eb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='文件資料夾'])[1]/following::a[1]</value>
      <webElementGuid>d4fe529c-9a4e-4521-bdaa-88208f463f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='首頁'])[1]/following::a[2]</value>
      <webElementGuid>ac15bd3e-71e4-4d0b-a188-198ba146842c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='文件資料夾'])[2]/preceding::a[2]</value>
      <webElementGuid>37843a2e-ba79-4f39-bf08-e5d30060356e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='過濾'])[1]/preceding::a[3]</value>
      <webElementGuid>d88eb881-98a4-4619-954a-ed596e45bcbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='會員顧客協議書']/parent::*</value>
      <webElementGuid>01b7f440-0117-42eb-8621-3312c2e07ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/enrollmentPage/')]</value>
      <webElementGuid>ecc83f40-f037-43bd-b1e7-615acfb23306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>c429c6e1-4d73-441f-b858-1e64e5cafee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/enrollmentPage/' and (text() = '會員顧客協議書' or . = '會員顧客協議書')]</value>
      <webElementGuid>9d13d14e-69e0-4469-b937-2b515166f56f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
