<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ (4)</name>
   <tag></tag>
   <elementGuidId>e1235793-d874-41b6-86b5-47587b2b076c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'會員顧客協議書')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.pure-menu-item.ng-scope > a.pure-menu-link.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c059ef9-365d-4c80-beef-80846291a0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/enrollmentPage/</value>
      <webElementGuid>7b4aa030-ddeb-4277-bb0b-a14249e0ade4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pure-menu-link ng-binding</value>
      <webElementGuid>0e5d6924-0113-4fa9-b025-3f4d946099e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>會員顧客協議書</value>
      <webElementGuid>6b040358-4ce4-444d-9d2d-ad1eec13fab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope&quot;]/header[1]/div[@class=&quot;menu-container pure-menu pure-menu-horizontal&quot;]/ul[@class=&quot;pure-menu-list&quot;]/li[@class=&quot;pure-menu-item pure-menu-has-children pure-menu-allow-hover&quot;]/ul[@class=&quot;pure-menu-children&quot;]/li[@class=&quot;pure-menu-item ng-scope&quot;]/a[@class=&quot;pure-menu-link ng-binding&quot;]</value>
      <webElementGuid>446575a6-1649-4804-bb54-cc5ab7b7b807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'會員顧客協議書')]</value>
      <webElementGuid>4c08eb60-8790-494e-ac3e-0de1a4f044ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='文件資料夾'])[1]/following::a[1]</value>
      <webElementGuid>c1df42bd-55ac-4e67-ba87-7c8fddc79e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='首頁'])[1]/following::a[2]</value>
      <webElementGuid>fe7e4f5c-fa3e-43bc-bc8d-4fb9d69ea8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='文件資料夾'])[2]/preceding::a[2]</value>
      <webElementGuid>94a32f42-9066-4478-b121-c0c25e5dd6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='過濾'])[1]/preceding::a[3]</value>
      <webElementGuid>78d01b80-a1f2-436a-8e22-24db8d96eee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='會員顧客協議書']/parent::*</value>
      <webElementGuid>492893ea-0229-4c6a-b76f-3746805042ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/enrollmentPage/')]</value>
      <webElementGuid>e9ae406b-b61a-48bb-a1d9-ecc3a9b29ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>a04004c8-0923-4f8e-9f13-63688e9628ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/enrollmentPage/' and (text() = '會員顧客協議書' or . = '會員顧客協議書')]</value>
      <webElementGuid>f3ea2335-da55-4400-b9fe-48edb79ee584</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
