<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_govermentId</name>
   <tag></tag>
   <elementGuidId>81f92311-c138-407c-8591-a4a2c72dc2b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txt_govermentId&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txt_govermentId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3bc74e9-80c1-40f2-a240-3e2acf295754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>7cd19261-27fe-45fc-90ba-b4a8398d0f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_govermentId</value>
      <webElementGuid>53bc4e4d-f516-4f3b-86fb-bec1e005b3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61be84d0-0dcf-4865-be0f-8ee3928a548a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>enrollment.CustomerData.GovernmentIdentification</value>
      <webElementGuid>216f19ea-ebbb-466d-8f6e-631c2a0741dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>UpperCaseGovernmentID()</value>
      <webElementGuid>eeb67f2e-9bc1-4efa-9f44-40583940dd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>身分證號碼</value>
      <webElementGuid>d8041c29-7e1b-4523-bfbb-9d53ab0a76ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>ValidateGovernmentIden()</value>
      <webElementGuid>a97ea98a-ac22-4f62-bc6a-249b0af14558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CMA&quot;)/div[1]/div[@class=&quot;CMA ng-scope&quot;]/fieldset[@class=&quot;group&quot;]/hongkong-customer-basic-info[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;col-md-12 clearBoth ng-invalid ng-invalid-required ng-valid-invalid-date-format ng-valid-email ng-dirty ng-valid-parse&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-md-2 ng-pristine ng-invalid ng-invalid-required&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>08d73361-421c-4ae9-a9c5-3b85fd44de18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txt_govermentId']</value>
      <webElementGuid>44dc3ab9-6801-4d33-8ee4-210000dd383d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CMA']/div/div/fieldset/hongkong-customer-basic-info/div/div/div[7]/input</value>
      <webElementGuid>09e2c470-2faf-4c5d-8200-5e263a81468a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>e9d7f196-e662-4fa0-b2df-c3f6ff5508ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txt_govermentId' and @type = 'text' and @placeholder = '身分證號碼']</value>
      <webElementGuid>51c06088-31f3-4d8b-99a2-896cf6b1b8cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
