<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_Enroller (1)</name>
   <tag></tag>
   <elementGuidId>349131f3-bf51-49f9-a025-f2e99704957b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='txt_Enroller'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0419bb45-4e15-4c01-9380-8a33ed862dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>2dbb408b-607a-41e8-8321-ca99b8a7839d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>搜尋</value>
      <webElementGuid>443da0e3-af2f-45a7-9ab1-c0f960b28ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_Enroller</value>
      <webElementGuid>281e8aa8-6cd8-44bd-a65b-8a083c2cd608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>enrollerMelaId</value>
      <webElementGuid>26b75934-0daa-42c8-9feb-58ce0f500c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>canInputEnroller</value>
      <webElementGuid>11f712f0-7613-4216-90a2-91cb37fa84d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keypress</name>
      <type>Main</type>
      <value>$event.keyCode == 13 &amp;&amp; SearchEnroller()</value>
      <webElementGuid>c42ebf77-3f39-4c91-b9d9-58f23f88cd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CMA&quot;)/div[1]/div[@class=&quot;CMA ng-scope&quot;]/fieldset[@class=&quot;col-md-12 clearBoth&quot;]/div[@class=&quot;group&quot;]/hongkong-organization[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;ng-pristine ng-invalid ng-invalid-required&quot;]/div[@class=&quot;form-group col-md-6 clearBoth ng-pristine ng-invalid ng-invalid-required&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>07ee2af7-61cd-4822-bf1b-64d27ae2cf8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='txt_Enroller'])[2]</value>
      <webElementGuid>401ef57d-f16d-4f05-b0a7-baad8f74c437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CMA']/div/div/fieldset[2]/div/hongkong-organization/div/div/div[2]/input</value>
      <webElementGuid>f8d6116b-9e1f-41d7-a023-d0aadec29b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//hongkong-organization/div/div/div[2]/input</value>
      <webElementGuid>f0a8b03a-b65b-4e32-8d24-336925905798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '搜尋' and @name = 'txt_Enroller']</value>
      <webElementGuid>952b1f84-de30-47a6-862d-0e612fda6a30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
