<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_mobileNumber</name>
   <tag></tag>
   <elementGuidId>9bc501d7-541f-43b8-9d0f-f9b984c5276c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txt_mobileNumber&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txt_mobileNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f36ec267-72fe-4bdc-a2c9-c699cc59f062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>3a15cab1-822f-4ddf-aba3-add1941d7d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_mobileNumber</value>
      <webElementGuid>415662f9-9577-489d-84ba-dd5bd34b2336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>device.PhoneNumber</value>
      <webElementGuid>9e3544a8-86a7-456a-8497-31aa33493148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>手提電話號碼</value>
      <webElementGuid>f57a0dd7-9bd9-4ca1-a985-d346fcbeca97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>999-9999-9999</value>
      <webElementGuid>50c0cd16-bb03-4b36-9bfa-13dc43d1c97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask-clean</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1069aca2-800e-46e0-b91e-487310819a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>validateMobilePhone(device);IsPhoneRequire(device);</value>
      <webElementGuid>13821249-a75a-40ec-ad21-a4b91820d286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CMA&quot;)/div[1]/div[@class=&quot;CMA ng-scope&quot;]/fieldset[@class=&quot;group&quot;]/hongkong-customer-basic-info[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;col-md-12 clearBoth ng-valid-email ng-dirty ng-valid-parse ng-valid-invalidgovernmentid ng-valid-required ng-valid-minimum-age-error ng-valid-mask ng-valid ng-valid-invalid-date-format&quot;]/div[@class=&quot;row ng-scope&quot;]/hongkong-phone[@class=&quot;ng-isolate-scope&quot;]/fieldset[@class=&quot;col-md-10 ng-pristine ng-valid ng-valid-email&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;form-group col-md-2 ng-scope&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>95603970-ce1e-4b61-bd3a-b6fb009d6870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txt_mobileNumber']</value>
      <webElementGuid>eddc9eab-9584-41ba-b82d-0f64d3ed4a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CMA']/div/div/fieldset/hongkong-customer-basic-info/div/div[2]/hongkong-phone/fieldset/div/div[3]/div/input</value>
      <webElementGuid>094685b9-3777-48af-ac38-3065a9584768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[3]/div/input</value>
      <webElementGuid>3ee0d5f7-ae52-43f2-9d57-a9bbf75c5bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txt_mobileNumber' and @placeholder = '手提電話號碼']</value>
      <webElementGuid>077c82ad-af6e-4ed0-b959-26eb560a36a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
