<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_010203040506070809101112</name>
   <tag></tag>
   <elementGuidId>da9ae3fc-ac31-4087-8c86-7a6b9ded069f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;txt_Inbound_Exp_Month&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='txt_Inbound_Exp_Month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c7b974da-1169-49f6-b958-ab9f9bd0861c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-required</value>
      <webElementGuid>28b002bc-01b0-4daa-aa5a-83cacead4b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_Inbound_Exp_Month</value>
      <webElementGuid>fa1ca111-52d6-4e8c-9432-9a9ac5b889da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>txt_Inbound_Exp_Month</value>
      <webElementGuid>52fba6c8-70f5-4963-b0a9-78f8693daa0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>changeMonth()</value>
      <webElementGuid>9a5a9f97-6f5a-41be-831f-3cd1d678bece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>option.value as option.text for option in monthList</value>
      <webElementGuid>87ad5c9d-0b3a-4358-af11-ae7e689cbe9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>010203040506070809101112</value>
      <webElementGuid>21ebd04b-cbab-483e-a694-9869aadf2b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseVisa&quot;)/div[@class=&quot;paymethodGroup ng-valid ng-valid-pattern ng-valid-required ng-dirty ng-valid-parse ng-valid-luhn-check-fail&quot;]/div[@class=&quot;form-group ng-pristine ng-valid col-md-2 ng-valid-required&quot;]/select[@class=&quot;form-control ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-required&quot;]</value>
      <webElementGuid>39abd22d-8b0f-45b9-b64c-04b64d6eec29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='txt_Inbound_Exp_Month']</value>
      <webElementGuid>4c2e3090-2f11-4e5f-aa12-e437da2063e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseVisa']/div/div[4]/select</value>
      <webElementGuid>f520fc2d-d282-4bcd-be2f-ae7084dbcdf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='到期月'])[1]/following::select[1]</value>
      <webElementGuid>e6e842d1-1399-461e-b091-1966f5f83b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='有效銀行'])[1]/following::select[1]</value>
      <webElementGuid>cc374827-797e-49e1-bb17-3b385fa4e836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='到期年份'])[1]/preceding::select[1]</value>
      <webElementGuid>97ff8512-dcea-49ac-bcf7-ae1cc37b2c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='需要'])[11]/preceding::select[2]</value>
      <webElementGuid>8faa210c-f926-43f5-bbac-5b2d60783d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>76db99c2-fb55-4969-9914-2a5511bfd977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txt_Inbound_Exp_Month' and (text() = '010203040506070809101112' or . = '010203040506070809101112')]</value>
      <webElementGuid>4ad68591-db6d-4776-8013-4ff4e5017e4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
