<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_present-slideshow</name>
   <tag></tag>
   <elementGuidId>eb4a7c9f-d99a-4b21-bd78-29b99d988205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div/div/div/div[2]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-present-slideshow.js-overview</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ae18e9f1-bf5d-4e20-9a34-dd9d95b759dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-present-slideshow js-overview</value>
      <webElementGuid>3aa36c13-9839-433a-b5dc-f4cd6b6f8f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tag</name>
      <type>Main</type>
      <value>OV Present Slideshow</value>
      <webElementGuid>87bbace8-0177-49ce-833c-5effbf12f30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>bd87e20b-bc9b-4ce3-8b62-f886711fdb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://online.flippingbook.com/view/122153/</value>
      <webElementGuid>6ce23685-fdf8-492a-9188-2d3ab30eac13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
               立即開始你的事業分享會

            </value>
      <webElementGuid>0a0fb9fa-4635-4c5a-abba-9d640ff92bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preRecordedOverview&quot;)/div[@class=&quot;flex&quot;]/section[@class=&quot;section section1&quot;]/a[@class=&quot;btn btn-present-slideshow js-overview&quot;]</value>
      <webElementGuid>9aeb745e-7265-44a0-8d02-a4075923b7b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='preRecordedOverview']/div/section/a</value>
      <webElementGuid>ff8bc539-f97c-4d98-b7ce-b035d803eb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'立即開始你的事業分享會')]</value>
      <webElementGuid>2692ed58-851f-4a8b-9d36-64620a0b5498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='所有成功的美樂家領導人都用此最有效的方式介紹美樂家'])[1]/following::a[1]</value>
      <webElementGuid>7f7b66fe-f743-4c37-8ac2-ca01314d64a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='認識美樂家手冊'])[1]/following::a[1]</value>
      <webElementGuid>d0d090d2-ad73-4354-94d6-c554a411a0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='您絕對可以'])[1]/preceding::a[1]</value>
      <webElementGuid>4214d8ef-1b13-4ac0-922c-569003231055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='立即開始你的事業分享會']/parent::*</value>
      <webElementGuid>1cc6e750-99c9-4a56-a291-cfe0b89feb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://online.flippingbook.com/view/122153/')]</value>
      <webElementGuid>47e9bd12-39c1-4767-9ed5-e2d03c950cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/a</value>
      <webElementGuid>5554f1e8-fbea-41b1-9fd1-5af624248daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://online.flippingbook.com/view/122153/' and (text() = '
               立即開始你的事業分享會

            ' or . = '
               立即開始你的事業分享會

            ')]</value>
      <webElementGuid>8d4102d0-77d4-4bc8-a2e8-417e503ade70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
