<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_present-slideshow</name>
   <tag></tag>
   <elementGuidId>eb4a7c9f-d99a-4b21-bd78-29b99d988205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div/div/main/div/section[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-present-slideshow.js-overview</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>542340b0-2d2e-4f5c-b7d7-b71345461c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-present-slideshow js-overview</value>
      <webElementGuid>7917904c-31bb-4017-9fbb-97f2c5df5ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tag</name>
      <type>Main</type>
      <value>OV Present Slideshow</value>
      <webElementGuid>2c1d96d3-5b60-4627-a5f0-0c0d136ae56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>22e56533-61a4-4b2f-9ff7-fc90d021e678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://online.flippingbook.com/view/122153/</value>
      <webElementGuid>8ca68eb7-a3bd-4779-8662-b4e4a02808d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
               立即開始你的事業分享會

            </value>
      <webElementGuid>973bdc36-967b-466d-8d13-428e8d56b510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preRecordedOverview&quot;)/div[@class=&quot;flex&quot;]/section[@class=&quot;section section1&quot;]/a[@class=&quot;btn btn-present-slideshow js-overview&quot;]</value>
      <webElementGuid>805fb6e6-99d2-42a4-9457-c666a49596e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='preRecordedOverview']/div/section/a</value>
      <webElementGuid>fdf3cf14-5f2b-4472-b2b5-8c827df5c80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'立即開始你的事業分享會')]</value>
      <webElementGuid>f484c877-0fa0-4cce-bb13-9f4046f0c5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='所有成功的美樂家領導人都用此最有效的方式介紹美樂家'])[1]/following::a[1]</value>
      <webElementGuid>5f8868d5-b2f3-484c-9888-4e271e6efbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='認識美樂家手冊'])[1]/following::a[1]</value>
      <webElementGuid>a872776f-ec3c-4771-a646-0a0f59d02435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='您絕對可以'])[1]/preceding::a[1]</value>
      <webElementGuid>3225035d-3667-48e1-8b3e-d0d551a4fdd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='立即開始你的事業分享會']/parent::*</value>
      <webElementGuid>2cf53842-5cc6-4375-8b62-de887c6b4573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://online.flippingbook.com/view/122153/')]</value>
      <webElementGuid>6641c5cb-e6f3-4a7d-9209-1640906ebd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/a</value>
      <webElementGuid>9e477a42-7d47-4f51-940f-032ee3d11b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://online.flippingbook.com/view/122153/' and (text() = '
               立即開始你的事業分享會

            ' or . = '
               立即開始你的事業分享會

            ')]</value>
      <webElementGuid>83c14a07-428e-422f-aa58-4ceb77f90d1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
