<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-sort-asc</name>
   <tag></tag>
   <elementGuidId>607abf1c-59fc-40a7-aebf-5ba09e0617c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dvInvitationList']/div[2]/div/div/div/span[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-sort-asc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-sort-asc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvInvitationList&quot;)/div[@class=&quot;customerList&quot;]/div[@class=&quot;headerRow&quot;]/div[@class=&quot;rowWrapper&quot;]/div[@class=&quot;header&quot;]/span[@class=&quot;ng-scope&quot;]/i[@class=&quot;fa fa-sort-asc&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvInvitationList']/div[2]/div/div/div/span[2]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span[2]/i</value>
   </webElementXpaths>
</WebElementEntity>
