<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_hk</name>
   <tag></tag>
   <elementGuidId>a555140b-7576-4dd4-874e-4671c179c942</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'globalCountryDropdownMobile' and (text() = '
    
            香港
' or . = '
    
            香港
')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#globalCountryDropdownMobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[3]/div/div/div[1]/div[1]/div[5]/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5a29398d-2be9-4ce1-89c6-b9e74e551884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>globalCountryDropdownMobile</value>
      <webElementGuid>e117c491-ce0e-4dd0-aa64-b74e4847e90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>preventChange(event);</value>
      <webElementGuid>c82b720e-d956-4895-abf5-0b69b2624d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>selectCountryCulture(this.value);return false;</value>
      <webElementGuid>83488276-8e31-43a8-831e-61f7eae548f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    
            香港
</value>
      <webElementGuid>2644b47a-9fc3-4fe0-877e-76f98edc65a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalCountryDropdownMobile&quot;)</value>
      <webElementGuid>bebdf9fc-4d1a-42b6-9fba-8201bf23bd94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='globalCountryDropdownMobile']</value>
      <webElementGuid>52c5c238-1ee6-4e58-be66-5b3998da7e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FTCenterContent54']/div[2]/select</value>
      <webElementGuid>79332cc4-30bb-4b9c-81ec-0601e4e31bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='選擇國家或地區語言：'])[1]/following::select[1]</value>
      <webElementGuid>f7d33d77-c588-4856-a86b-b3cbd024c0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='送貨地址功能更新及分區表'])[1]/following::select[1]</value>
      <webElementGuid>7ed90dfd-3eaf-416d-adec-344ab1ede977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='私隱政策'])[1]/preceding::select[1]</value>
      <webElementGuid>01fe414b-0e04-40c0-aa6c-3f025f06cbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>be297bf0-86e6-4461-9ae7-183cbca21cb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
