<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_Shipping_Address</name>
   <tag></tag>
   <elementGuidId>55ef86a8-cd7b-4c3b-a131-a6afc721f86e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_Shipping_Address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_Shipping_Address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e2e3d8c-9721-4953-a1ab-af3d40e1ee19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>2d0f8bc0-a816-4826-b984-a02de7412e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_Shipping_Address</value>
      <webElementGuid>4013c17c-f318-469b-ba4f-d5de15239092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_Shipping_Address</value>
      <webElementGuid>a90f57f2-a954-4e9b-af8b-f8addc66547f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>address.AddressLine1</value>
      <webElementGuid>5607a4fe-00ba-49a6-877e-3b6886fe751e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>大廈 / 屋苑 / 街道</value>
      <webElementGuid>e54077ed-1445-4d92-9f54-f6a1289c9a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_Shipping_Address&quot;)</value>
      <webElementGuid>af24f1d0-288f-4bdc-bfed-064e2218d8c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_Shipping_Address']</value>
      <webElementGuid>2b905af5-54f5-43fa-a66b-1c6de4bc75be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CMA']/div/div/hongkong-addresses/div/hongkong-shipping-address/fieldset/div/div/div/input</value>
      <webElementGuid>b350dc54-3b93-4ff6-8c18-ad82758a9c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//hongkong-shipping-address/fieldset/div/div/div/input</value>
      <webElementGuid>0776b7d2-a735-4ad6-b1be-7b986d1795d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txt_Shipping_Address' and @name = 'txt_Shipping_Address' and @placeholder = '大廈 / 屋苑 / 街道']</value>
      <webElementGuid>5d7959f2-8002-4ea7-a989-08f9174dae8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
