<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_Enroller_tw</name>
   <tag></tag>
   <elementGuidId>f54c2840-7fbd-435a-99c5-cfda3a451654</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CMA']/div/div/taiwan-organization/fieldset/div/div/div[2]/span[2]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9abbcb4b-ccea-43f6-a070-10108c212f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-search</value>
      <webElementGuid>762f1fb5-ffbd-4aa5-8cf9-69fbf51c7ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a79d8de8-7f04-41b5-a2bd-0e654dec6183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CMA&quot;)/div[1]/div[@class=&quot;CMA zh-TW ng-scope&quot;]/taiwan-organization[@class=&quot;ng-isolate-scope&quot;]/fieldset[@class=&quot;col-md-12 clearBoth&quot;]/div[@class=&quot;group ng-pristine ng-invalid ng-invalid-required&quot;]/div[@class=&quot;form-group col-md-6 clearBoth ng-pristine ng-invalid ng-invalid-required&quot;]/div[@class=&quot;input-group&quot;]/span[@class=&quot;input-group-btn&quot;]/button[@class=&quot;btn btn-default&quot;]/span[@class=&quot;fa fa-search&quot;]</value>
      <webElementGuid>ca237ddf-274b-49d2-9d0b-afcc636091bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CMA']/div/div/taiwan-organization/fieldset/div/div/div[2]/span[2]/button/span</value>
      <webElementGuid>0058e873-505e-4f27-8cc6-62438f461c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/button/span</value>
      <webElementGuid>17a92323-d22d-4dd3-8b33-5f0f68ef0d90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
