<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_closeLink</name>
   <tag></tag>
   <elementGuidId>9ee60519-5c92-49ae-95a7-f2eb8bdd87e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div/div/div[2]/div/div[1]/div[4]/div/div[7]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dvInviteConfirmation > div.displayPrompt > div.closeLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12b33404-a461-41e1-9455-dabc9c147f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>closeLink</value>
      <webElementGuid>d64ce87d-acdb-4cf8-8422-5ea110b9250f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>closePopup()</value>
      <webElementGuid>29259440-bd03-410a-8a2f-c37e308f4750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking</name>
      <type>Main</type>
      <value>X-Sent</value>
      <webElementGuid>bcb62216-06a7-4e3c-a150-efe915652e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvInviteConfirmation&quot;)/div[@class=&quot;displayPrompt&quot;]/div[@class=&quot;closeLink&quot;]</value>
      <webElementGuid>2af85993-b9a4-4a3c-b53f-20d22a8ebb16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvInviteConfirmation']/div/div</value>
      <webElementGuid>552dfb16-8d47-49d0-b92e-bdc0642bc940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div/div</value>
      <webElementGuid>af7bfb5b-dcff-4263-accd-fbb5dc80c2c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
