<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Paymethod_CreditCard_AccountNumber</name>
   <tag></tag>
   <elementGuidId>44b780b5-49ac-45a1-a157-63fc82a742da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PaymethodViewModel_CreditCardViewModel_AccountNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PaymethodViewModel_CreditCardViewModel_AccountNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3cb22c4-29af-48d6-b438-f07839eb4c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>creditCardAccountNumber</value>
      <webElementGuid>ccbf2ede-27c8-4d08-8796-6939e0f7c9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PaymethodViewModel_CreditCardViewModel_AccountNumber</value>
      <webElementGuid>a09dfcb9-d533-4c1d-b8b9-dc8d402df941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PaymethodViewModel.CreditCardViewModel.AccountNumber</value>
      <webElementGuid>994851e5-b93f-47f6-8176-b01f44b99c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>UpdateCvv();</value>
      <webElementGuid>a78b45a9-6d96-489a-9a9e-8ed406a0a912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>59d218a2-ce71-4858-af1e-2fd9f6ed9bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PaymethodViewModel_CreditCardViewModel_AccountNumber&quot;)</value>
      <webElementGuid>b534e0f8-02ba-45d6-9def-8010cd8bea53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PaymethodViewModel_CreditCardViewModel_AccountNumber']</value>
      <webElementGuid>b7bbc273-456b-4ba7-a52c-7dd1ea2ea040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='savePrimaryCreditCard']/div/div[2]/div/div[4]/input</value>
      <webElementGuid>46010864-3ecd-4425-a141-b5254d798c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>5df73c3b-ca2f-4505-88ed-01bb7272349b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
