<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GovernmentId</name>
   <tag></tag>
   <elementGuidId>518183e5-b93c-4ccc-b9aa-ed51ec6f3205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GovernmentId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GovernmentId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41692d11-b5ee-4d29-b9cd-8dc29eadcb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GovernmentId</value>
      <webElementGuid>69289680-783c-4be3-bdfd-3fe1aa766049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GovernmentId</value>
      <webElementGuid>7b9e39fb-4d03-41f2-9652-f6c8ece98156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5863c5ca-ca9e-4ebb-9098-ef61597dd422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GovernmentId&quot;)</value>
      <webElementGuid>4607abef-bcec-4583-a048-4609b5635612</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GovernmentId']</value>
      <webElementGuid>a795ea65-3957-4429-9b60-303d0563a3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customerInformationForm']/div/div[8]/div/div/div[2]/input</value>
      <webElementGuid>c3cdb7e3-db9d-41b1-882b-31bfcbcfb4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/input</value>
      <webElementGuid>3b8d33b0-37f6-4098-82fc-aa9ce614ab46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
