<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Paymethod_CreditCard_AccountHolderName</name>
   <tag></tag>
   <elementGuidId>9fec0a6e-7e5f-4aeb-8c27-f7ac9ddce0a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PaymethodViewModel_CreditCardViewModel_AccountHolderName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PaymethodViewModel_CreditCardViewModel_AccountHolderName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c11d0d8a-ef47-4352-80a4-d359c3eec7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>creditCardHolderName</value>
      <webElementGuid>e8b3d108-982b-48f6-a87f-a5545b8d938d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PaymethodViewModel_CreditCardViewModel_AccountHolderName</value>
      <webElementGuid>2afc13cd-6978-4a4a-98ef-9ec20b87ca7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PaymethodViewModel.CreditCardViewModel.AccountHolderName</value>
      <webElementGuid>e572baec-b6c1-45c3-8213-a5cc293ddc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b2cae3ce-4035-4d10-9028-92bfd32d3d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PaymethodViewModel_CreditCardViewModel_AccountHolderName&quot;)</value>
      <webElementGuid>16da7958-b470-481e-b688-9d0ceeace73e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PaymethodViewModel_CreditCardViewModel_AccountHolderName']</value>
      <webElementGuid>e75d79ea-5268-4095-a9b2-3fa978f13906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='savePrimaryCreditCard']/div/div/div[2]/input</value>
      <webElementGuid>14ac4272-534e-49de-93e4-afcb6686c0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/div[2]/input</value>
      <webElementGuid>9684b80c-3cb8-43c8-94f2-4e17492bc459</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
