<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtNewEnrolleeFirstName</name>
   <tag></tag>
   <elementGuidId>304ae59f-2a20-4734-8d98-9ace63c9fdc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNewEnrolleeFirstName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtNewEnrolleeFirstName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac8b44ba-5de0-4ed7-8c28-87c5ffa1e9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNewEnrolleeFirstName</value>
      <webElementGuid>d95a9aa8-7d6b-4db7-a6f4-4402f64a5edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ac81be5-e0e0-44d8-b211-0469ffea1c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'invalid': missingInviteFirstName}</value>
      <webElementGuid>937a9457-ab06-492d-a522-5d2a7f2c4e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>enrollee.FirstName</value>
      <webElementGuid>53059451-04a8-4ccf-bc31-a4cf7f8d05b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid</value>
      <webElementGuid>f576c322-d673-41e4-8f6a-6f6b9b174bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNewEnrolleeFirstName&quot;)</value>
      <webElementGuid>42dc980c-3ae0-4a01-a915-0fd9a1c852b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNewEnrolleeFirstName']</value>
      <webElementGuid>bfd63eed-344e-458a-9c62-b600f5e499fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvStartNewEnrollment']/div/div[4]/div/input</value>
      <webElementGuid>dd768430-c658-40f5-b4b4-b41b5e588e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>8599232e-6a86-413c-958c-5b695f8f9c38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
