<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_BusinessCenter_OLE_EditPresenter</name>
   <tag></tag>
   <elementGuidId>f74e9560-37a5-417c-8d8b-413b232a1527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dvStartNewEnrollment']/div/div[5]/div/div[2]/div[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>de1c1804-6842-464f-b964-c2ced605590b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chkVerifyPresenter</value>
      <webElementGuid>f89c603b-4869-4f26-8a1a-e612aee2822d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'invalid': missingPresenterConfirm}</value>
      <webElementGuid>77a707ad-b33b-4c33-abb5-52c83d3c0546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-bind-html</name>
      <type>Main</type>
      <value>localizations.verifyPresenter</value>
      <webElementGuid>d79247ac-afe0-4214-845e-7975cab60957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>0dfd54fb-d693-44d1-b77a-1fa2d4059443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>我確認是由此位協助推薦人幫助我介紹美樂家相關資訊給新會員</value>
      <webElementGuid>1ea836aa-0ea8-4b86-b6bb-c295ced80c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvStartNewEnrollment&quot;)/div[@class=&quot;displayPrompt&quot;]/div[@class=&quot;presenterInfo&quot;]/div[@class=&quot;dataWrapper&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;presenterCheckContainer confirmation&quot;]/label[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>bebb8a15-fb42-416a-8ec6-d75d01a1e8c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvStartNewEnrollment']/div/div[5]/div/div[2]/div[3]/label</value>
      <webElementGuid>0f9c69d1-1144-4b76-a34d-379a36fe4c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='編輯'])[1]/following::label[1]</value>
      <webElementGuid>5eb91478-57fd-47cc-9dbc-fc79ac9b1120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='輔導事業代表'])[1]/preceding::label[1]</value>
      <webElementGuid>41b63ebd-d959-414b-b7f6-68c6bf09664c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EH 2.2 HK Test'])[2]/preceding::label[1]</value>
      <webElementGuid>2013e668-88af-4580-bfd0-69a4561991aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='我確認是由此位協助推薦人幫助我介紹美樂家相關資訊給新會員']/parent::*</value>
      <webElementGuid>35ac9e7c-857a-4fbb-937e-20f233e7e62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>e70dadd0-cb68-4ac3-866e-8385ad9d5868</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
