<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BusinessCenter_OLE_CityCtrl</name>
   <tag></tag>
   <elementGuidId>39aa9daa-4446-40c6-b5d9-0b5993fa5602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CityCtrl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CityCtrl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>470f10a3-8205-4c4a-8f08-1286ba2f74e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CityCtrl</value>
      <webElementGuid>7a8f03ce-d6fb-4496-b7c0-fed901b762d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CityCtrl</value>
      <webElementGuid>4c4140a1-4d0b-4d42-bbeb-6bcefb30128b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gray-default-option</value>
      <webElementGuid>7b951e9e-9151-4180-bb1f-e493f39eae5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>選擇台北市基隆市新北市連江縣宜蘭縣釣魚台新竹市新竹縣桃園市苗栗縣台中市彰化縣南投縣嘉義市嘉義縣雲林縣台南市高雄市南海島澎湖縣金門縣屏東縣台東縣花蓮縣</value>
      <webElementGuid>770b1ebb-3aae-452e-86bf-bcd7aa214a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CityCtrl&quot;)</value>
      <webElementGuid>6d9a6f86-7088-4383-a851-febd95c3da61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CityCtrl']</value>
      <webElementGuid>3a35b518-3cce-4630-9594-db8427c56c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addressForm']/div/div/div/div[2]/div/select</value>
      <webElementGuid>92d2303d-6e1e-4088-b1a6-cb1d4ef8d9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='縣市*'])[1]/following::select[1]</value>
      <webElementGuid>565fac8f-1561-47bf-ab50-47563f832e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='戶籍地址'])[1]/following::select[1]</value>
      <webElementGuid>c9638efc-5929-4b06-bf70-ca0d85a4c4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='區鄉鎮村*'])[1]/preceding::select[1]</value>
      <webElementGuid>1f6cd410-db2a-44fd-9fa9-642615c74ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='省市*'])[1]/preceding::select[2]</value>
      <webElementGuid>bc96b5ba-4ed5-4d8d-8bef-e5d1d4b866e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div[2]/div/select</value>
      <webElementGuid>3087d45e-57d4-4d8b-9493-d2fd596bcae7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
