<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add New Shipping Address</name>
   <tag></tag>
   <elementGuidId>f2283ae3-adad-4833-9f68-0b5c8f08040b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/div/div/section[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.o-acctCardSection__addNewBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>28a9c0ec-5bd8-41b1-a7b1-7b213d5af444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/my-account/payments-and-addresses/add-new-shipping-address</value>
      <webElementGuid>a2684bb5-cbdf-4673-b4d0-6c855d296e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-acctCardSection__addNewBtn</value>
      <webElementGuid>e9dbbc89-7fa4-4a52-9aa7-f960efeef28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+Add New Shipping Address
        </value>
      <webElementGuid>18a309bc-b9f9-44ec-9956-1469a435f13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[1]/div[@class=&quot;o-widthControl mx-auto w-full max-w-full to-md:px-10 md:max-w-contain md:py-40&quot;]/section[@class=&quot;o-acctCardSection&quot;]/div[@class=&quot;lg:pr-20 lg:w-1_2&quot;]/a[@class=&quot;o-acctCardSection__addNewBtn&quot;]</value>
      <webElementGuid>1315eef3-4e8a-45ec-a10a-db4591c753fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/div/section[2]/div/a</value>
      <webElementGuid>211e857c-7f3c-4480-9fa8-7d3281062470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You cannot delete a Default Address. Edit another address and make default.'])[1]/following::a[1]</value>
      <webElementGuid>79ee81e9-9872-4e43-a939-c3dfdd675f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::a[1]</value>
      <webElementGuid>36d6f364-9859-4f89-93dd-459b8c655c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commission Deposit Account'])[1]/preceding::a[1]</value>
      <webElementGuid>915ff8ee-d79e-4df8-975d-35c16c7b013d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add New Shipping Address']/parent::*</value>
      <webElementGuid>e18db548-972e-4135-91c9-7e82891ab0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/my-account/payments-and-addresses/add-new-shipping-address')]</value>
      <webElementGuid>8511caa2-8c2d-4fc4-8e67-c6274ebe2e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/a</value>
      <webElementGuid>419db554-a0ee-4225-b099-2fd4b8643460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/my-account/payments-and-addresses/add-new-shipping-address' and (text() = '+Add New Shipping Address
        ' or . = '+Add New Shipping Address
        ')]</value>
      <webElementGuid>53ae7ffc-6c86-4046-bbd2-9030e6828244</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
