<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_See All_o-myAccPopup__icon loaded</name>
   <tag></tag>
   <elementGuidId>ef410027-9993-4a5f-b789-cb6c66def6bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vApp']/div/header/div[2]/div[5]/div[4]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.o-myAccPopup__icon.loaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8d3a7f64-2f64-454e-acf5-6f4d8230a3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>My Account Popup Button</value>
      <webElementGuid>f50a9323-6609-4cc0-b015-4fda8db2b0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-myAccPopup__icon loaded</value>
      <webElementGuid>3311f61f-3311-4845-94dd-fbcea0d109d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdnsc1.melaleuca.com/cdn-cgi/image/quality=85/sg-my/images/header/icon-account-2.png</value>
      <webElementGuid>925048cd-0b77-4d51-940a-f9dc85b1279d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>dfcf743f-d797-4828-aea6-d8d3449f5c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vApp&quot;)/div[@class=&quot;bg-gray-25&quot;]/header[@class=&quot;o-siteHeader&quot;]/div[@class=&quot;o-siteHeader__row -main&quot;]/div[@class=&quot;o-siteHeader__col -actions&quot;]/div[@class=&quot;o-myAccPopup&quot;]/button[@class=&quot;o-myAccPopup__btn&quot;]/img[@class=&quot;o-myAccPopup__icon loaded&quot;]</value>
      <webElementGuid>c804db6b-4949-42b3-bdd3-5c5d30cad617</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vApp']/div/header/div[2]/div[5]/div[4]/button/img</value>
      <webElementGuid>7ee76c53-0434-4290-8991-164c625ea1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='My Account Popup Button']</value>
      <webElementGuid>f78e908b-bb47-49f6-81b1-937e02031a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/img</value>
      <webElementGuid>56f02ea0-944c-47cb-a853-e7bca6c85e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'My Account Popup Button' and @src = 'https://cdnsc1.melaleuca.com/cdn-cgi/image/quality=85/sg-my/images/header/icon-account-2.png']</value>
      <webElementGuid>d4dcdde3-f878-4e21-bff7-c7fa99e1e7e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
