<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_GENERATE</name>
   <tag></tag>
   <elementGuidId>3119b061-f4c4-4337-b67a-56cbba122ba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div/div[2]/div[1]/div/div[2]/div/div[1]/form/div[5]/div/div[2]/a/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#namso-atag > b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>8dfc193e-66d7-4ada-926a-1399983a4990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GENERATE</value>
      <webElementGuid>7fc0807c-98f6-4728-abb4-7718e795e24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namso-atag&quot;)/b[1]</value>
      <webElementGuid>ae4cf42d-a0ca-43cc-8212-e915a4269618</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='namso-atag']/b</value>
      <webElementGuid>35e8b2ee-869c-4cc6-b58c-0cc6a84e942f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FORMAT'])[1]/following::b[1]</value>
      <webElementGuid>04e820f4-1f06-40d0-8bb6-e3acf78e64bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUANTITY'])[1]/following::b[1]</value>
      <webElementGuid>3207fc1c-0287-42ce-bf9f-53d11ceac465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRAND'])[1]/preceding::b[1]</value>
      <webElementGuid>7f504270-54f1-4323-832e-404d3168b3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::b[1]</value>
      <webElementGuid>ecc8e1eb-2f3f-4cea-8161-37edf39396ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GENERATE']/parent::*</value>
      <webElementGuid>7236f26f-1e37-42f2-8fe8-a8975afedc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/b</value>
      <webElementGuid>1ec5ee07-c94e-4eb1-bef2-dd26898c28b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'GENERATE' or . = 'GENERATE')]</value>
      <webElementGuid>57bb2574-7238-4cc7-8f71-f1cdbf448b60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
