<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Saving Packs  Bundles</name>
   <tag></tag>
   <elementGuidId>86d82eeb-89c7-4855-94a8-2a67c2d4bbb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.m-navMenu__item.-lvl2.Both > a.m-navMenu__item-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/header/div[2]/div[2]/nav/div/div[1]/div/div/div/ul/li[2]/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c099cc5-2f90-417d-91ff-dec1e66aea3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/productstore/supplements/saving-packs-and-bundles</value>
      <webElementGuid>ec8f8759-3ba0-4a03-baf5-41bd8f0d8f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>|Custom</value>
      <webElementGuid>4aa439e7-892b-457e-a65a-e6f7104743e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>25a69ef7-ef8c-4046-9ae9-03049f1d8b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>235ae255-4abb-443a-b1a6-53340fd4c5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2500637c-f5b6-48b0-820c-773a6754aa7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-navMenu__item-btn</value>
      <webElementGuid>985cc9fe-7c7b-4f07-86d5-da1fcaa2e734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0ef6d371-4f1d-4d7e-bfcd-d021ab57e71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saving Packs &amp; Bundles </value>
      <webElementGuid>e5402034-0649-4698-bafd-332236b814c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lvlABA3802E67CA411F976187D19A456DE5&quot;)/li[@class=&quot;m-navMenu__item -lvl2 Both&quot;]/a[@class=&quot;m-navMenu__item-btn&quot;]</value>
      <webElementGuid>35f8f0c7-0d6b-47bb-a707-e33c94e6a1f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='lvlABA3802E67CA411F976187D19A456DE5']/li[3]/a</value>
      <webElementGuid>7c0fdc05-6123-412d-8744-e5f41af3a0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Saving Packs &amp; Bundles')]</value>
      <webElementGuid>781c3c29-a61b-445d-8bc7-4ee80c18cfca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Supplements'])[1]/following::a[1]</value>
      <webElementGuid>d6788635-4f3b-4591-b7d6-7657bd32e160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back To Main'])[1]/following::a[2]</value>
      <webElementGuid>b8c7e604-8d09-4727-a154-a4e7691dd4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cleaning and Laundry'])[1]/preceding::a[1]</value>
      <webElementGuid>173c7748-f6f1-4878-8cef-234d4e7c862b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back To Main'])[2]/preceding::a[2]</value>
      <webElementGuid>a40d0817-840d-46e3-9aa0-374a11371793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saving Packs &amp; Bundles']/parent::*</value>
      <webElementGuid>4721aee6-1a77-4d63-a827-6eab6cd50655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/productstore/supplements/saving-packs-and-bundles')]</value>
      <webElementGuid>af61d02e-253a-486d-a3f2-5983589604f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li[3]/a</value>
      <webElementGuid>e986fb36-53e1-4df4-88b8-be95af78db6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/productstore/supplements/saving-packs-and-bundles' and (text() = 'Saving Packs &amp; Bundles ' or . = 'Saving Packs &amp; Bundles ')]</value>
      <webElementGuid>4162c816-10eb-446f-b7b3-e6b789e0d6ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
