<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go To My Account</name>
   <tag></tag>
   <elementGuidId>85cb8c29-9f2e-4e7a-bdff-b75c99de51ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vApp']/div/header/div[2]/div[5]/div[4]/div/div/div[2]/div/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06381772-b79d-4361-8488-8940794bd61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/my-account</value>
      <webElementGuid>6e185a09-7e0c-40db-9240-ccc4ad7f6ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-myAccPopup__link</value>
      <webElementGuid>dd614e11-2aac-4df4-82f9-c56d06867a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go To My Account</value>
      <webElementGuid>c882155b-e95f-4a54-9fcd-6846cef2728f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vApp&quot;)/div[@class=&quot;bg-gray-25&quot;]/header[@class=&quot;o-siteHeader&quot;]/div[@class=&quot;o-siteHeader__row -main&quot;]/div[@class=&quot;o-siteHeader__col -actions&quot;]/div[@class=&quot;o-myAccPopup&quot;]/div[@class=&quot;m-popUp top-40 right-25&quot;]/div[@class=&quot;m-popUp__content&quot;]/div[@class=&quot;m-popUp__body pb-16 pl-24 pr-16&quot;]/div[@class=&quot;m-myAccPopup&quot;]/a[@class=&quot;m-myAccPopup__link&quot;]</value>
      <webElementGuid>ec77d8a5-2ea2-4d7e-8408-a9e8bf4db844</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vApp']/div/header/div[2]/div[5]/div[4]/div/div/div[2]/div/a[4]</value>
      <webElementGuid>083187f7-3277-4e9d-96aa-c9c7764ebfbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Go To My Account')]</value>
      <webElementGuid>7907fdf1-bdac-4c4a-afc6-dcf62d194c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Backup Order'])[2]/following::a[1]</value>
      <webElementGuid>a2fdc63f-ab56-4f63-b7a3-3e2968e71e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Preferences'])[2]/following::a[2]</value>
      <webElementGuid>ffdf6282-d993-4fae-9d99-405f7c80e3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[2]/preceding::a[1]</value>
      <webElementGuid>7d7f8fc6-a47a-4bce-8140-c7b0df076ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shopping_cart'])[1]/preceding::a[2]</value>
      <webElementGuid>af47bd00-32a2-48e9-9ca6-e150967ed618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go To My Account']/parent::*</value>
      <webElementGuid>b8ac06dc-021d-4bb2-9952-a42e538658a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/my-account')])[15]</value>
      <webElementGuid>7db38bcf-dcdb-4016-8763-8ea508c499c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>e461b950-92f4-4d2f-898d-8ced9cf11c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/my-account' and (text() = 'Go To My Account' or . = 'Go To My Account')]</value>
      <webElementGuid>50b96d5f-30e9-4703-b7c8-211abf4aa028</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
