<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BusinessCenter_tw</name>
   <tag></tag>
   <elementGuidId>7ab517bc-f8e1-4e16-872c-5ed6bcbcc263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[1]/div[3]/div[1]/ul/li[3]/a/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menuItem_2 > div.nav-root-item-inner-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9bb5cb71-6827-4234-b68c-0b311cf712c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-root-item-inner-wrapper</value>
      <webElementGuid>1d0b0acb-f546-4c61-a360-12d353435135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>事業中心</value>
      <webElementGuid>c0ca756a-8a49-4bd1-9d2d-6969bb990ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuItem_2&quot;)/div[@class=&quot;nav-root-item-inner-wrapper&quot;]</value>
      <webElementGuid>f4b1690a-496a-4e56-9a9a-799a7dc7461f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuItem_2']/div</value>
      <webElementGuid>930010f9-2071-430d-8c27-f603a7d9b3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='永恆卡方案'])[1]/following::div[2]</value>
      <webElementGuid>97c29feb-13e7-4528-8729-6014b97d8606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='產品中心'])[1]/following::div[4]</value>
      <webElementGuid>56427bbc-cfc0-4d02-b7c9-05f2845cbbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='關於美樂家'])[1]/preceding::div[2]</value>
      <webElementGuid>9333ed44-5c71-40f8-b589-937b331582f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='事業中心']/parent::*</value>
      <webElementGuid>abb59a4f-b0a5-4dde-998c-e4602c40ab3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div</value>
      <webElementGuid>9e7d7604-e544-4156-bea6-2b45278c2492</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
