<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__fa fa-times-circle lists__remove-icon</name>
   <tag></tag>
   <elementGuidId>89bcff2b-8eb3-41a4-854a-20018a83ba32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopping-list-page-app']/div/div[2]/list-search-dropdown/div[2]/div[2]/form/ul/div/li/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.lists__ul__my-lists.js-editing-my-lists.ng-scope > i.fa.fa-times-circle.lists__remove-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times-circle lists__remove-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>removeTheList(list.listId)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-list-page-app&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;list-container ng-scope&quot;]/list-search-dropdown[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;below-tabs&quot;]/div[@class=&quot;lists-options lists-options-editable js-lists-options-editable active ng-pristine ng-valid&quot;]/form[@class=&quot;ng-pristine ng-valid&quot;]/ul[@class=&quot;lists__ul lists__ul-edit js-ul-edit&quot;]/div[@class=&quot;lists__limiting-bottom-lists js-scroll-lists&quot;]/li[@class=&quot;lists__ul__my-lists js-editing-my-lists ng-scope&quot;]/i[@class=&quot;fa fa-times-circle lists__remove-icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopping-list-page-app']/div/div[2]/list-search-dropdown/div[2]/div[2]/form/ul/div/li/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li/i</value>
   </webElementXpaths>
</WebElementEntity>
