<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Payment Methods</name>
   <tag></tag>
   <elementGuidId>2d252f4f-75fa-444e-ab39-2ad4821d8896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='lvl9D4004E624F348039EC7151FF5BD321C']/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>80fcf1b2-a637-4bbe-bc5a-8f8cc857380d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/my-account/payments-and-addresses</value>
      <webElementGuid>87117f14-d064-4fa3-a3db-b9573c17d0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>|Custom</value>
      <webElementGuid>3248ed9d-c70c-47cf-b733-f9ab81c22c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0fa123a1-3d6f-4a5d-be77-f1b760c62464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>1fa3153f-ca88-4ab4-aaea-702b8da7edf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5a2aa6f3-eb2d-46e1-ba8b-cb1ff2dbebe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-navMenu__item-btn</value>
      <webElementGuid>8e706407-2322-483a-bb5d-0a1a35629b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b18ff128-acd1-4c56-b744-178dfe28d7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment Methods </value>
      <webElementGuid>03f769be-7bcb-480f-b1a6-53ae31a5c028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lvl9D4004E624F348039EC7151FF5BD321C&quot;)/li[@class=&quot;m-navMenu__item -lvl2 Both&quot;]/a[@class=&quot;m-navMenu__item-btn&quot;]</value>
      <webElementGuid>4c4b2704-e60a-4e16-a9c8-8b95a7861b3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='lvl9D4004E624F348039EC7151FF5BD321C']/li[5]/a</value>
      <webElementGuid>eb901f37-e0d2-4cc0-ad1c-d67a5c9a104a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Payment Methods')]</value>
      <webElementGuid>9b9a68ec-e819-4cd7-ba42-112b33c4b5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Lists'])[1]/following::a[1]</value>
      <webElementGuid>7f739dff-c559-4600-8809-066e9f5b2e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order History'])[1]/following::a[2]</value>
      <webElementGuid>308b1774-6d31-4e11-a6a0-c886f62f2328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Preferences'])[1]/preceding::a[1]</value>
      <webElementGuid>22e3b729-3829-4aa1-b9d7-e9351494c71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Backup Order'])[1]/preceding::a[2]</value>
      <webElementGuid>6ca79323-5229-400d-b38b-ec4e5bb74af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payment Methods']/parent::*</value>
      <webElementGuid>be5aa64e-c9dc-4e21-a85e-6eef23c74dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/my-account/payments-and-addresses')]</value>
      <webElementGuid>d04ea89f-4a7b-4fbb-bd54-f9ee052a210f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/div/ul/li[5]/a</value>
      <webElementGuid>f1134ca4-efbe-4c58-ad8a-15b9fad5615f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/my-account/payments-and-addresses' and (text() = 'Payment Methods ' or . = 'Payment Methods ')]</value>
      <webElementGuid>69c8e2f6-28b8-4017-ae84-cca1352dc054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
