<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BusinessCenter_OLE_ConfirmDetails_Continue</name>
   <tag></tag>
   <elementGuidId>553d7c1c-03f2-4f3a-bfc9-0b79af5d1090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnSaveButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnSaveButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2735f2ea-dcb2-4809-bc56-d34f6a1b1f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveButton</value>
      <webElementGuid>ce942603-419f-44e2-b59c-38a226407187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'disabled': presenter.isInSearchMode || manager.isInSearchMode}</value>
      <webElementGuid>055818b4-f302-4d69-ad92-b39126cadaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button pure-button-green ng-binding</value>
      <webElementGuid>a07bc752-ad30-4527-aa62-52410034e29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>saveChanges();</value>
      <webElementGuid>5086b6b9-e3b1-4a98-8027-1e5a1833c925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    繼續
                </value>
      <webElementGuid>04aa3740-849d-4a99-99f0-e164a54b565c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSaveButton&quot;)</value>
      <webElementGuid>1d0b9986-17d5-4af7-9ee1-b505a42f624c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btnSaveButton']</value>
      <webElementGuid>d6cdfc13-7389-4aee-9758-2bf4cd001f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formWrapper']/div[5]/div/div</value>
      <webElementGuid>7a6ef6b8-b0ed-421d-8ca2-0ed9ae92452a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='協助組織發展的夥伴/領導人'])[1]/following::div[4]</value>
      <webElementGuid>976c0ff5-4552-4077-a484-23a56112823a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='編輯'])[2]/following::div[5]</value>
      <webElementGuid>400dcadd-6a6c-4e58-96fd-89d9c8e33bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='請再試'])[1]/preceding::div[1]</value>
      <webElementGuid>3f4b51f3-8877-4342-8864-c7e1d673a6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='繼續']/parent::*</value>
      <webElementGuid>fe792ca1-a1f1-492e-9db0-67408c439c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[5]/div/div</value>
      <webElementGuid>a405cafa-c48a-4a10-a48b-29216840d770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'btnSaveButton' and (text() = '
                    繼續
                ' or . = '
                    繼續
                ')]</value>
      <webElementGuid>223d170f-8076-4404-874b-5de5a19cbc98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
