<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BusinessCenter_OLE_ConfirmDetails_SearchSuppleTeam_Cancel</name>
   <tag></tag>
   <elementGuidId>09dcb984-5376-4b0a-bb77-fab9bcc6ce45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dvSupportTeamSearch']/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cancelSearchLink.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb52b750-196a-4148-b4d8-6d847f090840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cancelSearchLink ng-binding</value>
      <webElementGuid>6612160a-9253-4258-ad20-642bf42bafd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>togglePresenterSearch()</value>
      <webElementGuid>03ea36aa-7c88-469e-8439-55acf988f8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>取消</value>
      <webElementGuid>fc03a3f0-8395-4c82-acf7-0b316ba5c9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvPresenterSearch&quot;)/div[@class=&quot;cancelSearchLink ng-binding&quot;]</value>
      <webElementGuid>98bf2cd9-260b-4a8a-8a2c-37e2f8ee3bb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvPresenterSearch']/div[4]</value>
      <webElementGuid>e49759d8-b37c-4dbc-91f0-2c7f71a4fcb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestHK PCR'])[1]/following::div[1]</value>
      <webElementGuid>d34fb8cb-b35c-4da1-96b9-119dc77a532f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='搜尋'])[1]/following::div[5]</value>
      <webElementGuid>840dc679-8db6-4ec3-93ab-a1d371571920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='輔導事業代表'])[1]/preceding::div[1]</value>
      <webElementGuid>779b8d7c-3ee2-4e7f-8228-7f0869e21a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tw50550556'])[1]/preceding::div[2]</value>
      <webElementGuid>7de0893c-8310-4420-920d-97a2142f3685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='取消']/parent::*</value>
      <webElementGuid>1ea67191-e150-48d4-829e-b72524779407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[3]/div[4]</value>
      <webElementGuid>abec97ae-a952-4885-906b-f9b82ddbf62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '取消' or . = '取消')]</value>
      <webElementGuid>412c5a8a-449f-4837-8bc1-9cc29f116b4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
