<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_BusinessCenter_OLE_ConfirmDetails_Presenter_Edit</name>
   <tag></tag>
   <elementGuidId>5b0dab8c-e782-45ad-a4de-f1b23378d546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '編輯' or . = '編輯')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dvPresenter']/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pencilEditText.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0298b96a-c95e-4dcf-8f17-5cf611cab0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pencilEditText ng-binding</value>
      <webElementGuid>3afb9421-82ac-4518-9848-0aae781b2f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>編輯</value>
      <webElementGuid>86934a03-815e-47ec-a0ea-045ae04dcc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvPresenter&quot;)/span[@class=&quot;greenIcon&quot;]/span[@class=&quot;pencilEditText ng-binding&quot;]</value>
      <webElementGuid>8eb833da-46f3-4d96-bf46-9e4ea6c7fa5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvPresenter']/span[2]/span</value>
      <webElementGuid>989d5615-09f4-4ba6-99fd-07066a9347e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestHK PCR'])[1]/following::span[2]</value>
      <webElementGuid>0131c78d-7307-40d3-abda-12ef8755675b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='協助推薦人'])[1]/following::span[3]</value>
      <webElementGuid>244e4575-c817-432e-8b7e-8991c5397ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='協助說明美樂家會員權益者'])[1]/preceding::span[1]</value>
      <webElementGuid>7610393b-2f13-4dfe-b22f-e6f75ebe0d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='輔導事業代表'])[1]/preceding::span[1]</value>
      <webElementGuid>84dc3496-d794-4e62-9eca-36e89e0be70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='編輯']/parent::*</value>
      <webElementGuid>7e5bc01c-c3b5-4aed-aaba-219b9b51805e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]/span</value>
      <webElementGuid>56f16256-b062-4131-912c-f6684cbff7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '編輯' or . = '編輯')]</value>
      <webElementGuid>66c44601-3a57-448b-ae66-2cdd28c7478e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
