<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout_tw</name>
   <tag></tag>
   <elementGuidId>dedb3c33-a136-4d4d-a5b8-69f007c46b76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/Shared/SignOut.aspx' and @id = 'nav-menu-signout-btn' and (text() = '登出' or . = '登出')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[1]/div[2]/div[1]/div[5]/a

</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-menu-signout-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0efbe52a-e4cc-4677-8f67-db658f4076ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Shared/SignOut.aspx</value>
      <webElementGuid>0d927f9d-afc7-409b-9181-bafdcb5533d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-menu-signout-btn</value>
      <webElementGuid>770f4c62-dbd4-49c9-92f1-30f4a4279832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-link light-text</value>
      <webElementGuid>af652e1a-f3ff-4aeb-892f-7514953a7789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>登出</value>
      <webElementGuid>c7d8a287-5f85-42ca-942e-bfce8cbeaae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-signout-btn&quot;)</value>
      <webElementGuid>0367a3aa-c49b-4a88-bb18-c266eac71bd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-menu-signout-btn']</value>
      <webElementGuid>dc34d0b8-ef21-45f4-aac6-af793e22f444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menubar1']/div[5]/a</value>
      <webElementGuid>67875cfe-6fcc-4326-881f-92a7d41b7d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'登出')]</value>
      <webElementGuid>ba381a5b-90e7-4265-8b8e-826c118bbf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='服務中心'])[1]/following::a[1]</value>
      <webElementGuid>329ab9b6-a39e-4961-824a-9180ee1df9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=': NT$5,292'])[1]/following::a[2]</value>
      <webElementGuid>d417c001-44c7-4fe8-b080-2e404c9b412c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='登出']/parent::*</value>
      <webElementGuid>4fd4a6b6-3b46-4842-bc37-3f6aa5b93579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Shared/SignOut.aspx')]</value>
      <webElementGuid>5e91bff4-a041-473b-80c5-0a6b5b3478f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>c75e9913-2dbe-41cb-9456-791302c76f90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
