<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BusinessCenter_OLE_DCSelect</name>
   <tag></tag>
   <elementGuidId>b778dc2f-3310-4739-a210-14a930013176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div[2]/div[3]/div[2]/div/div/section[3]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '選擇
            沒有折扣' or . = '選擇
            沒有折扣')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c6aefb5-63ae-49f5-959c-02f2e36bb7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('#submitDirectForm').submit(); cmCreateElementTag('RegularCustomerSelectConfirm', analyticsElementCategory);</value>
      <webElementGuid>04196ae9-17f4-4b6b-8fe3-c9d9c2d06264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ole-action ole-action--button</value>
      <webElementGuid>80501c1a-d77f-49e2-94c2-c6bf84cacbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>選擇
            沒有折扣</value>
      <webElementGuid>36eefe58-96a4-49b6-8fb5-0bd53c08b394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;main-container desktop zh-TW&quot;]/div[@class=&quot;customer-type&quot;]/div[@class=&quot;contentDisplay&quot;]/div[@class=&quot;ole-container ole-container--customer&quot;]/div[@class=&quot;ole-pop-up-modal is-active&quot;]/section[@class=&quot;ole-section ole-section--button-wrapper cf&quot;]/button[@class=&quot;ole-action ole-action--button&quot;]</value>
      <webElementGuid>cc9a7da1-b282-4b49-9ef3-6e76a82e5062</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;$('#submitDirectForm').submit(); cmCreateElementTag('RegularCustomerSelectConfirm', analyticsElementCategory);&quot;]</value>
      <webElementGuid>6f445677-a380-4c7c-beb1-f7a84f03afc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div[2]/div[3]/div[2]/div/div/section[3]/button[2]</value>
      <webElementGuid>7232b376-68b1-4694-bdc9-0ad5b27ceced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='返回'])[1]/following::button[1]</value>
      <webElementGuid>a4ea1df9-cf20-43c6-8d98-5b8baaf5edf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='您真的不想在美樂家享受五折到七折的優惠嗎？'])[1]/following::button[2]</value>
      <webElementGuid>8eeacbe8-6768-44b9-a3aa-254c6e3195dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='消費回饋'])[1]/preceding::button[1]</value>
      <webElementGuid>e1303142-ea8e-4100-b08c-aec196630a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='美樂家刊物'])[1]/preceding::button[1]</value>
      <webElementGuid>9c6aea8b-9c24-48e7-9db2-fb84f215d247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>8278edfb-d5ff-41c8-a7c3-7082c4cb260c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
