<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BusinessCenter_OLE_Invitation_CancelResend</name>
   <tag></tag>
   <elementGuidId>8f0c5600-9524-4fa8-8abb-79df324fb28a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div/div/div[2]/div/div[1]/div[1]/div/div[5]/div[2]/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnCancelResend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cdac5e82-6c60-4e7d-b263-06b0a8853fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCancelResend</value>
      <webElementGuid>ee5392bd-7651-4d97-89ba-0983db5488f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button whiteButton ng-binding</value>
      <webElementGuid>ea48d4d2-a940-4f77-a577-2f66c5b78405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>closePopup()</value>
      <webElementGuid>72a97b61-f42a-4922-8cd6-d7e26bc75042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>關閉</value>
      <webElementGuid>de147b96-59b1-45d6-bbf3-e8246500666d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCancelResend&quot;)</value>
      <webElementGuid>4806daf9-40ac-402b-9824-901e3456654d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btnCancelResend']</value>
      <webElementGuid>d9d53884-cd7f-4c1a-9c51-1a8232a8d573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvViewContactInfo']/div/div[5]/div[2]/div/div</value>
      <webElementGuid>55ecab65-24b1-4094-a4e1-aed3e46799a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tw918211?'])[1]/following::div[3]</value>
      <webElementGuid>2c5c47a0-ea68-4fb8-959d-4840bd3186b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='電子信箱'])[1]/preceding::div[1]</value>
      <webElementGuid>c2fe23ac-1890-4e51-b6d2-e68f2e9c4584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div</value>
      <webElementGuid>41bf5f28-6d5e-4c78-844d-86b210d8fe79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
