<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_link startEnrollmentLink</name>
   <tag></tag>
   <elementGuidId>57a082d8-21e2-4a48-b5af-3b2a677bcbe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.link.startEnrollmentLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div/div/div[2]/div/div[4]/div[1]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;dvNewEnrollment&quot;)/div[@class=&quot;enrollmentLinks&quot;]/div[@class=&quot;enrollmentLink large&quot;]/div[@class=&quot;link startEnrollmentLink&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d33cbd35-b78f-4665-8488-d2eb83b6734f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link startEnrollmentLink</value>
      <webElementGuid>e1aebcf9-87d0-45ac-95d6-a6f5c648ae79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvNewEnrollment&quot;)/div[@class=&quot;enrollmentLinks&quot;]/div[@class=&quot;enrollmentLink large&quot;]/div[@class=&quot;link startEnrollmentLink&quot;]</value>
      <webElementGuid>b6202e74-8f08-4cd6-aa9f-0444726c6ba6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvNewEnrollment']/div[4]/div/div</value>
      <webElementGuid>1f8a952c-f185-4cd9-a037-5f42bf15fa32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[4]/div/div</value>
      <webElementGuid>14777155-96d3-4c31-9c68-beeda6ff0993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
