<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_link presentationLink</name>
   <tag></tag>
   <elementGuidId>f0c390c9-2ad2-4456-9120-d129ef740df6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div/div/div[2]/div/div[4]/div[2]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;dvNewEnrollment&quot;)/div[@class=&quot;enrollmentLinks&quot;]/div[@class=&quot;enrollmentLink&quot;]/div[@class=&quot;link presentationLink&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.link.presentationLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22d820e9-955e-46ad-8079-8c5c389a4af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link presentationLink</value>
      <webElementGuid>16f88a03-de4e-426a-be89-b8af7e360885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvNewEnrollment&quot;)/div[@class=&quot;enrollmentLinks&quot;]/div[@class=&quot;enrollmentLink&quot;]/div[@class=&quot;link presentationLink&quot;]</value>
      <webElementGuid>066ebe12-30c1-4f6c-bd4d-b0849dde98d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvNewEnrollment']/div[4]/div[2]/div</value>
      <webElementGuid>41a0c4a0-1068-4e07-a4a1-16bb60909843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div[2]/div</value>
      <webElementGuid>b3b1d953-775d-46cf-adab-3aa80994030d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
