<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_link startEnrollmentLink</name>
   <tag></tag>
   <elementGuidId>57a082d8-21e2-4a48-b5af-3b2a677bcbe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;dvNewEnrollment&quot;)/div[@class=&quot;enrollmentLinks&quot;]/div[@class=&quot;enrollmentLink large&quot;]/div[@class=&quot;link startEnrollmentLink&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dvNewEnrollment']/div[4]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.link.startEnrollmentLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c6b787c-cf2b-428d-84b1-eef0023539a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link startEnrollmentLink</value>
      <webElementGuid>4947b165-7927-470c-9f88-96cd76bce592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvNewEnrollment&quot;)/div[@class=&quot;enrollmentLinks&quot;]/div[@class=&quot;enrollmentLink large&quot;]/div[@class=&quot;link startEnrollmentLink&quot;]</value>
      <webElementGuid>28363f7a-0586-4d02-99b4-658692267eea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvNewEnrollment']/div[4]/div/div</value>
      <webElementGuid>331e5db7-75f2-458e-8f0e-9c7569069384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[4]/div/div</value>
      <webElementGuid>a6e77791-7f75-46dc-a2f6-ee34a19aeba7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
