<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-eye-slash_2</name>
   <tag></tag>
   <elementGuidId>fbfe826f-8d1a-4250-b690-5e57bd13c4ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;customerInformationForm&quot;)/div[@class=&quot;enrollee-info&quot;]/div[@class=&quot;inputRow passwordContainer&quot;]/div[@class=&quot;passwordInput&quot;]/div[@class=&quot;input-field-wrapper&quot;]/span[@class=&quot;showPassword&quot;]/i[@class=&quot;fa fa-eye-slash&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='customerInformationForm']/div/div[3]/div[3]/div[2]/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye-slash</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerInformationForm&quot;)/div[@class=&quot;enrollee-info&quot;]/div[@class=&quot;inputRow passwordContainer&quot;]/div[@class=&quot;passwordInput&quot;]/div[@class=&quot;input-field-wrapper&quot;]/span[@class=&quot;showPassword&quot;]/i[@class=&quot;fa fa-eye-slash&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customerInformationForm']/div/div[3]/div[3]/div[2]/span/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/span/i</value>
   </webElementXpaths>
</WebElementEntity>
