<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtMobilePhone2</name>
   <tag></tag>
   <elementGuidId>72db6baa-551e-421f-9e18-2c4d89b9bddd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'txtMobilePhone']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMobilePhone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtMobilePhone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf30605c-d91e-4073-8416-37fa7d1658db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1162c244-d206-4b41-8e98-fe71cd0858dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMobilePhone</value>
      <webElementGuid>c2c6e9b5-fbb4-4c2f-8123-d21a88cd8981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>formatPhoneNumber(false)</value>
      <webElementGuid>e8e001b5-2975-42e3-96a7-91366739319a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'invalid': missingInvitePhone}</value>
      <webElementGuid>82cc36d8-e504-4d69-af27-21290ed7c20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>enrollee.PhoneNumber</value>
      <webElementGuid>813f5bd8-dd6f-45b1-bd39-d241904e380d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid</value>
      <webElementGuid>0d1e528f-2340-4d31-9731-1bb7f4fa373a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvStartNewEnrollment&quot;)/div[@class=&quot;displayPrompt&quot;]/div[@class=&quot;customerInfoContainer&quot;]/div[@class=&quot;customerInfo ng-scope&quot;]/input[@id=&quot;txtMobilePhone&quot;]</value>
      <webElementGuid>ebcb138e-88b3-4256-858a-3941bacf1dd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMobilePhone']</value>
      <webElementGuid>283435d7-16e3-488e-9944-3d9d6d34686e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvStartNewEnrollment']/div/div[4]/div[3]/input</value>
      <webElementGuid>3fc5a364-1278-4371-bc99-0b24f1a145c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>d5f0dc3b-4545-424d-8fbd-1c47c85a2532</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
