<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ BusinessCenter_OLE_Invitation_Region</name>
   <tag></tag>
   <elementGuidId>1ae07793-f97f-44ad-b155-7661a9ec77c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='contactRegion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contactRegion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9ff0c62e-2608-44cf-85bf-5d04e0da6680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contactRegion</value>
      <webElementGuid>9b825d76-324e-40e1-90b5-464bdbc866b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>presentationSelection ng-pristine ng-valid</value>
      <webElementGuid>a3802693-3b81-49ba-a4ff-51732598a00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>contact.RegionDescription</value>
      <webElementGuid>45106a0b-b5c3-403d-a73c-5573903f83b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>changeRegion()</value>
      <webElementGuid>38473877-482e-4c2c-82ac-9cc070862846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>region.RegionDescription as region.RegionDescription for region in regionOptions</value>
      <webElementGuid>f452965c-09c7-4d66-a047-d1a0d3436b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>台灣香港</value>
      <webElementGuid>b9d04a07-107e-4c24-99db-55f3e6a73756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contactRegion&quot;)</value>
      <webElementGuid>552b95b7-a3f7-42d1-86c6-b8daf1811d30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='contactRegion']</value>
      <webElementGuid>07500c1a-8efa-466f-9b86-88a838befc4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvEditContactInfo']/div/div[4]/div[5]/select</value>
      <webElementGuid>a5b18d8b-37ab-4b7f-97c8-60016de0ef35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='地區'])[2]/following::select[1]</value>
      <webElementGuid>c1df8470-adfa-4bac-ab7f-3f2c82c5e1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='手機號碼'])[2]/following::select[1]</value>
      <webElementGuid>c6d57cc8-9de9-4a97-a027-8e4d87d4ee63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='取消'])[2]/preceding::select[1]</value>
      <webElementGuid>3f6bde74-1555-44e7-93c5-e679e11abd41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='儲存'])[1]/preceding::select[1]</value>
      <webElementGuid>eec67da9-ada0-4c38-b6dc-ee73c6de4736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>1ea43f18-4abd-4d45-881a-f4b4055d18d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
