<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_fa fa-plus-circle</name>
   <tag></tag>
   <elementGuidId>65e3138c-829b-4ad4-9b00-26b04698f900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-plus-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div/div[1]/div[4]/span/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>67d72c1e-e613-4022-80ae-4845e5cd59d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus-circle</value>
      <webElementGuid>973e3d97-57c9-4ab4-bea4-ab1928024910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shoppingListWrapper&quot;)/div[@class=&quot;contentDisplay&quot;]/button[@class=&quot;add-to-list-btn js-add-to-list&quot;]/span[@class=&quot;fa fa-plus-circle&quot;]</value>
      <webElementGuid>18f050e3-c9f9-4959-8408-a25e0cfaf05a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='shoppingListWrapper']/div/button/span</value>
      <webElementGuid>069293e0-de7b-474b-8e70-2732cd7ab75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/button/span</value>
      <webElementGuid>9d85ebdd-9c3c-4f12-a184-1545f8b2692d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
