<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__fa fa-user (1)</name>
   <tag></tag>
   <elementGuidId>243dfbc5-9471-4cad-9da2-6fa7702d4599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CMA']/div/div/taiwan-organization/fieldset/div/div[5]/div[2]/span[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8ae72a79-6363-40fe-84d3-3016ad038b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-user</value>
      <webElementGuid>43198d09-6b7f-47ba-b91a-70da38bbb4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CMA&quot;)/div[1]/div[@class=&quot;CMA zh-TW ng-scope&quot;]/taiwan-organization[@class=&quot;ng-isolate-scope&quot;]/fieldset[@class=&quot;col-md-12 clearBoth&quot;]/div[@class=&quot;group ng-pristine ng-invalid ng-invalid-required&quot;]/div[@class=&quot;form-group col-md-6 clearBoth ng-pristine ng-valid ng-valid-required&quot;]/div[@class=&quot;input-group&quot;]/span[@class=&quot;input-group-btn&quot;]/button[@class=&quot;btn btn-default&quot;]/span[@class=&quot;fa fa-user&quot;]</value>
      <webElementGuid>034fa440-e59e-4486-8c0c-ee50e561b96c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CMA']/div/div/taiwan-organization/fieldset/div/div[5]/div[2]/span[2]/button/span</value>
      <webElementGuid>5d14b52f-6905-4eaa-8539-fec99374545a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/span[2]/button/span</value>
      <webElementGuid>1d6c7358-c668-4c76-ae15-878231918a77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
