<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All Beauty</name>
   <tag></tag>
   <elementGuidId>a14b0d6e-341f-421a-9eaf-f05d8bfc2424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='lvl24C4BACF59E74B178A02FC14DDDF30AD']/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lvl24C4BACF59E74B178A02FC14DDDF30AD > li.m-navMenu__list.-title > a.block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ef5d85fb-a768-454e-a099-c4007f32f95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/productstore/sei-bella-beauty</value>
      <webElementGuid>2ce03994-34a3-4f26-9a4c-df14c4179455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block</value>
      <webElementGuid>e1b79c8a-416e-46eb-88ab-e878e34aff95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Beauty</value>
      <webElementGuid>1018d54b-6333-4214-95f3-8dacd4d09588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lvl24C4BACF59E74B178A02FC14DDDF30AD&quot;)/li[@class=&quot;m-navMenu__list -title&quot;]/a[@class=&quot;block&quot;]</value>
      <webElementGuid>bc21409c-b9fb-4d56-9831-572db618187e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='lvl24C4BACF59E74B178A02FC14DDDF30AD']/li[2]/a</value>
      <webElementGuid>5223e060-3b9a-41eb-ac5e-7197d032b578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'All Beauty')]</value>
      <webElementGuid>b5c1bd73-59be-4ece-b279-8ec49a33411f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back To Main'])[4]/following::a[1]</value>
      <webElementGuid>ac1351ad-9609-4e8d-bacf-b5e337a4e569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outdoor'])[1]/following::a[2]</value>
      <webElementGuid>c8b980cb-7024-43e9-b800-599b0efd81de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color Cosmetics'])[1]/preceding::a[1]</value>
      <webElementGuid>8878c4f4-9988-4020-af40-532726d1926f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Premium Skin Care'])[1]/preceding::a[2]</value>
      <webElementGuid>df0e59ab-81fd-4122-8aee-ecd225a296fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Beauty']/parent::*</value>
      <webElementGuid>7fde70ed-a5f3-43bf-96aa-557cd5a012c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/productstore/sei-bella-beauty')]</value>
      <webElementGuid>7c137dfb-734c-4cb2-b182-a28dcb58b07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/ul/li[2]/a</value>
      <webElementGuid>f45f8a9e-866f-4272-8d51-36ea19df34af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/productstore/sei-bella-beauty' and (text() = 'All Beauty' or . = 'All Beauty')]</value>
      <webElementGuid>700df8ac-8ab9-4b54-8b44-5f39d333e41f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
