<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Loyalty Shopping Dollars</name>
   <tag></tag>
   <elementGuidId>244b450e-a485-4ce8-a75a-ce586b614ae3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='lvl9D4004E624F348039EC7151FF5BD321C']/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d868aed2-7424-4776-a064-efaf498bf646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/loyalty-shopping-dollars</value>
      <webElementGuid>3046586a-355a-4cbc-a73c-8d85143cd522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2992d7e5-fc05-4e7f-9cf5-d96c91edd935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>c3286a02-926d-48e2-8809-ecd92705bc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f20d8376-0fb9-4978-a6d0-6abad0f4036d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-navMenu__item-btn</value>
      <webElementGuid>88678a3c-4d08-450c-b5ce-9125a676513c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3263c35a-6d20-4968-9819-1a1c0fd2e547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loyalty Shopping Dollars </value>
      <webElementGuid>8a7e612d-e61f-43f5-a27e-76c0a151bb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lvl9D4004E624F348039EC7151FF5BD321C&quot;)/li[@class=&quot;m-navMenu__item -lvl2 Both&quot;]/a[@class=&quot;m-navMenu__item-btn&quot;]</value>
      <webElementGuid>850583d8-a034-4c6e-9450-603717a55049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='lvl9D4004E624F348039EC7151FF5BD321C']/li[8]/a</value>
      <webElementGuid>d8b56d39-26f6-4c2b-a8e8-8aaa24126b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Loyalty Shopping Dollars')]</value>
      <webElementGuid>44d8c3fa-14f6-4555-8aeb-3752233ed286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Backup Order'])[1]/following::a[1]</value>
      <webElementGuid>6e7f08c9-04be-47fa-8067-822d4ba47a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Preferences'])[1]/following::a[2]</value>
      <webElementGuid>373096c5-3315-4d1c-a922-ec85a55976d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Story'])[2]/preceding::a[1]</value>
      <webElementGuid>0e4d1b8d-7400-4537-8ffe-322a01b559eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rewards'])[2]/preceding::a[2]</value>
      <webElementGuid>a9521507-c856-4e67-a074-5f558e774d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/loyalty-shopping-dollars')]</value>
      <webElementGuid>5ff0b53a-36b2-48ab-be2c-f75396a36cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/div/ul/li[8]/a</value>
      <webElementGuid>a079ee42-e281-4ee2-9c0c-38cc77a0cf1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/loyalty-shopping-dollars' and (text() = 'Loyalty Shopping Dollars ' or . = 'Loyalty Shopping Dollars ')]</value>
      <webElementGuid>1b79413b-7479-4e44-9568-6c3e0d48ae18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
