<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>282a0855-a7bf-41d7-bf11-f809fa5608c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.m-po__third-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='0']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96a49261-7851-4f15-99d8-ce62a835072f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/receipt?orderId=12529908</value>
      <webElementGuid>08d30f45-221b-4e10-add1-bbd89fc8f288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>See Full Order Receipt for order number 12529908</value>
      <webElementGuid>600a3ce8-ca85-4c9e-88a7-64dda508ff92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-po__third-title</value>
      <webElementGuid>366da2fa-982a-423b-9dad-9f0c044fbd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>注文明細を見る
</value>
      <webElementGuid>429f3355-dc5c-44c8-aa72-9d93bba30c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0&quot;)/a[@class=&quot;m-po__third-title&quot;]</value>
      <webElementGuid>82c36ade-c8e4-4046-b9f2-76c298084597</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='0']/a</value>
      <webElementGuid>ed7f4994-7d55-449c-b376-cef945a162a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'注文明細を見る')]</value>
      <webElementGuid>3dc40b53-f8b4-4879-8b40-6b96effd6cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='処理中'])[1]/following::a[1]</value>
      <webElementGuid>4e948f55-1d2a-4c7b-9912-69897cfa074e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='注文をカートに入れる'])[1]/following::a[1]</value>
      <webElementGuid>a6c6576e-faff-4fb6-bc52-902c02e67c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='横浜市港北区, 神奈川県 2220033'])[1]/preceding::a[1]</value>
      <webElementGuid>162f9237-5374-417e-9384-b125920380f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='注文明細を見る']/parent::*</value>
      <webElementGuid>cf52563b-37bd-4f58-9e4e-41b6fdf7fa06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/receipt?orderId=12529908')]</value>
      <webElementGuid>f4052021-2509-4182-b730-cf6738ac30ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/a</value>
      <webElementGuid>ef5ffe99-75cb-42b0-a58b-b34e3b6ae8c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/receipt?orderId=12529908' and (text() = '注文明細を見る
' or . = '注文明細を見る
')]</value>
      <webElementGuid>2b1c49a8-8efa-47c8-a8e5-626351333b1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
