<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_cancel-order</name>
   <tag></tag>
   <elementGuidId>23452f98-f552-4e18-ae3c-94f5b036d5fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.underline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/main/div[1]/div[2]/div[1]/table/tbody/tr/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>279ec686-9025-4599-a34e-6ee45c397abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline</value>
      <webElementGuid>10f4cf19-941c-435e-9662-d75e2092ea8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        取消訂單
                    </value>
      <webElementGuid>61c1f0f0-eb35-4f4c-b794-98289324d5b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;p-balance&quot;]/div[@class=&quot;p-balance__content&quot;]/div[@class=&quot;m-balanceTable&quot;]/table[@class=&quot;m-balanceTable__table&quot;]/tbody[@class=&quot;m-balanceTable__body&quot;]/tr[@class=&quot;m-balanceTable__row&quot;]/td[@class=&quot;m-balanceTable__col -cancel&quot;]/a[@class=&quot;underline&quot;]</value>
      <webElementGuid>bce3a46d-19e7-4b50-bb6b-0487313fb81e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/div[2]/div/table/tbody/tr/td[3]/a</value>
      <webElementGuid>97b96f2c-ee05-4ebe-94f9-5e3fb2c332a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'取消訂單')]</value>
      <webElementGuid>69b5330a-a0ee-4b33-bdd1-6db3c0b531d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='到期日:'])[1]/following::a[2]</value>
      <webElementGuid>fbbc3490-273f-4df3-8ccf-bf5bae0f19bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='訂單號碼:'])[1]/following::a[2]</value>
      <webElementGuid>48aef50f-1c21-4b85-923d-6b10c370b134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NT$4,030'])[1]/preceding::a[1]</value>
      <webElementGuid>84a91858-29e7-4584-bdcc-aa0963863c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='未付款總額:'])[1]/preceding::a[1]</value>
      <webElementGuid>55e8e8b3-6f7a-4817-a027-59e0d7c75c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='取消訂單']/parent::*</value>
      <webElementGuid>5fd296e6-5881-4ef6-893f-24fee4d53553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>3dfe2550-0159-43b5-8dda-31dbe73cbea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
                        取消訂單
                    ' or . = '
                        取消訂單
                    ')]</value>
      <webElementGuid>256bb763-d6ad-4adb-a5d2-4ed4cba251b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
