<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_edit-payment-method</name>
   <tag></tag>
   <elementGuidId>8e3491fe-8a9e-4046-85ac-fe73807cbfa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/main/div[1]/div/section[1]/ul/li[4]/div/div[1]/ul/li[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d9ca4d25-359c-4c77-a733-4bc025d103c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/my-account/payments-and-addresses/edit-payment-method?paymethodid=1222609517</value>
      <webElementGuid>5e6568e1-9f31-4cb9-b842-8c937e747bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>編輯付款方式 3002</value>
      <webElementGuid>6993c60b-d30b-4e82-bbdf-ccaab81b8873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    編輯

                </value>
      <webElementGuid>32010f6a-abc5-43b1-a946-2e1fcb13468d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[1]/div[@class=&quot;o-widthControl mx-auto w-full max-w-full to-md:px-10 md:max-w-contain md:py-40&quot;]/section[@class=&quot;o-acctCardSection&quot;]/ul[@class=&quot;o-acctCardSection__list&quot;]/li[@class=&quot;o-acctCardSection__col&quot;]/div[@class=&quot;m-acctCard&quot;]/div[@class=&quot;m-acctCard__card&quot;]/ul[@class=&quot;m-acctCard__actions&quot;]/li[@class=&quot;m-acctCard__button&quot;]/a[1]</value>
      <webElementGuid>0d33cfea-24f3-4ed7-9718-98bb94bc09ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/div/section/ul/li[4]/div/div/ul/li/a</value>
      <webElementGuid>d0122f46-6230-4adb-ae02-2e008df102e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'編輯')])[4]</value>
      <webElementGuid>1271c243-169a-4d5d-b54d-b25cbc983ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='····'])[2]/following::a[1]</value>
      <webElementGuid>7cd4a90c-750d-4608-b7f8-9fb2fbb3b27b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='刪除'])[1]/preceding::a[1]</value>
      <webElementGuid>a1c78b80-188b-4c9e-90d4-88bfde221240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='設為預設'])[4]/preceding::a[1]</value>
      <webElementGuid>0fb171d0-8c5c-44b0-88a4-8c0608f1da41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/my-account/payments-and-addresses/edit-payment-method?paymethodid=1222609517')]</value>
      <webElementGuid>7585320a-d299-480b-873d-8201a59eb57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/ul/li/a</value>
      <webElementGuid>c1b7085c-e3c9-4e0a-a385-781a04d9a50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/my-account/payments-and-addresses/edit-payment-method?paymethodid=1222609517' and (text() = '
                    編輯

                ' or . = '
                    編輯

                ')]</value>
      <webElementGuid>985ccecc-94a1-4559-9101-d3f890dd84b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
