<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_lacto-ovo-protein</name>
   <tag></tag>
   <elementGuidId>6362dc3a-3515-4411-b293-b11a44549433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lvl36A0705C425F4CB1BA310A2BB22034B9 > li.m-navMenu__item.-lvl2.Both > a.m-navMenu__item-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='lvl36A0705C425F4CB1BA310A2BB22034B9']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e529eca7-930d-4323-95d5-20c677f4ecc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/productstore/vegetarian/other-vegetarian</value>
      <webElementGuid>218f103c-7933-4eed-a5eb-41cc51e996ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e85790a1-832b-4572-9a85-fbd61c3d356f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>671988de-b9b4-4dcb-9f60-006c8bf79e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fae338ad-fed0-4ef4-8cf1-5a2b9f4746c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-navMenu__item-btn</value>
      <webElementGuid>d5653424-d07e-4ebc-b7fc-24e171f04631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c067d220-0575-4de2-bf64-3aaf89a62fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>五辛素/奶蛋素 </value>
      <webElementGuid>93642dfb-719f-44c5-a2f7-42235d6a8296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lvl36A0705C425F4CB1BA310A2BB22034B9&quot;)/li[@class=&quot;m-navMenu__item -lvl2 Both&quot;]/a[@class=&quot;m-navMenu__item-btn&quot;]</value>
      <webElementGuid>34bde227-22ff-4840-a384-0431b7e1a411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='lvl36A0705C425F4CB1BA310A2BB22034B9']/li[4]/a</value>
      <webElementGuid>531712bd-e360-4681-b1c4-1e8df50eb72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'五辛素/奶蛋素')]</value>
      <webElementGuid>30e41499-356e-4a52-8a72-e0f15d8a03bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='奶素'])[2]/following::a[1]</value>
      <webElementGuid>724d6788-8a17-4c00-84d5-429ac595208f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='素食'])[2]/following::a[2]</value>
      <webElementGuid>22808413-90a8-447a-bf41-34f743a32c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全素'])[1]/preceding::a[1]</value>
      <webElementGuid>1f8ad6c4-eb51-416d-9446-455aefc520da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='家用清潔'])[1]/preceding::a[2]</value>
      <webElementGuid>e4635f86-36ce-4ea9-9d0a-8b50f529287f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='五辛素/奶蛋素']/parent::*</value>
      <webElementGuid>6f86885c-3f4e-4fbd-a984-a789937e97e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/productstore/vegetarian/other-vegetarian')]</value>
      <webElementGuid>ae622db8-1cdb-4a6d-9df1-8d0832936917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/ul/li[4]/a</value>
      <webElementGuid>210b5075-4242-452f-9686-d563ece5d1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/productstore/vegetarian/other-vegetarian' and (text() = '五辛素/奶蛋素 ' or . = '五辛素/奶蛋素 ')]</value>
      <webElementGuid>e5ed8235-0d78-454c-bbb4-47387a433d56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
