<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_menu_tracking list</name>
   <tag></tag>
   <elementGuidId>bd275a5d-2e23-4b19-80ba-ecf5ba4356f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lvlAC952C31777749569E02C66CA1F30E01 > li.m-navMenu__item.-lvl2.Both > a.m-navMenu__item-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='lvlAC952C31777749569E02C66CA1F30E01']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>478cf219-b02a-44a7-ae5b-7a39151d10a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/my-account/lists</value>
      <webElementGuid>310bf0ad-6a7b-4f06-8b4a-cee25817b264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5348e038-6510-4911-ad87-9e108b55d3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>7ec5948d-b490-4ab9-ba81-949013aaa2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6e445c25-fc79-416a-8c23-980d73537f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-navMenu__item-btn</value>
      <webElementGuid>c6cf56b1-39cb-4ff8-a074-7717a10565c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e8148944-3149-4cd4-b241-0547e039a9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>追蹤清單 </value>
      <webElementGuid>cbaf1e24-311b-4b7c-9cd5-2133a2cd7229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lvlAC952C31777749569E02C66CA1F30E01&quot;)/li[@class=&quot;m-navMenu__item -lvl2 Both&quot;]/a[@class=&quot;m-navMenu__item-btn&quot;]</value>
      <webElementGuid>fa7204f6-f45a-4635-bad4-b1aae82205a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='lvlAC952C31777749569E02C66CA1F30E01']/li[4]/a</value>
      <webElementGuid>e8411121-45b4-44c2-8fb2-86f77d81610b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'追蹤清單')]</value>
      <webElementGuid>43968ac6-93b7-4598-bad3-6b64eef6c4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='訂單紀錄'])[2]/following::a[1]</value>
      <webElementGuid>c3d83b10-fd04-4fde-a0ac-994118866456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我的帳戶'])[3]/following::a[2]</value>
      <webElementGuid>e1e5121b-2fd1-4ad2-af9c-afa406dfef1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='付款及地址管理'])[1]/preceding::a[1]</value>
      <webElementGuid>5501de4f-69a9-4707-88f4-d2a8e8903e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='帳戶設定'])[1]/preceding::a[2]</value>
      <webElementGuid>e1d42d7e-0114-416d-bcf7-fd60f95fd485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='追蹤清單']/parent::*</value>
      <webElementGuid>cc6669f5-8019-47ab-894a-07cf715a21e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/my-account/lists')])[2]</value>
      <webElementGuid>4adf726a-4bba-44bf-9231-f030c37cce11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/div/ul/li[4]/a</value>
      <webElementGuid>e449a011-1937-4a25-bda8-750561169459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/my-account/lists' and (text() = '追蹤清單 ' or . = '追蹤清單 ')]</value>
      <webElementGuid>f711f3e9-4944-4018-8818-c9d7ca930fb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
