<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_my account</name>
   <tag></tag>
   <elementGuidId>78d22dbc-97ea-43d9-8f61-6987f9ab08a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lvlAC952C31777749569E02C66CA1F30E01 > li.m-navMenu__list.-title > a.block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='lvlAC952C31777749569E02C66CA1F30E01']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25ac1e5e-710a-4175-bdca-f7d26b97a9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/my-account</value>
      <webElementGuid>1271a03d-d44a-4175-ad06-cd28c6b4bfa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block</value>
      <webElementGuid>aa675cfa-da5e-4dfa-a572-5015dc6c4c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>我的帳戶</value>
      <webElementGuid>ae617db5-aa7e-4b27-87dd-8272d9b84d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lvlAC952C31777749569E02C66CA1F30E01&quot;)/li[@class=&quot;m-navMenu__list -title&quot;]/a[@class=&quot;block&quot;]</value>
      <webElementGuid>460e8cac-0735-439f-939c-1ae66242951b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='lvlAC952C31777749569E02C66CA1F30E01']/li[2]/a</value>
      <webElementGuid>045fa3f7-32eb-489e-9959-9ee3e43d9466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'我的帳戶')])[3]</value>
      <webElementGuid>10d621aa-4ce5-4586-91b4-18c7731afc23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='回上一頁'])[8]/following::a[1]</value>
      <webElementGuid>f2360e18-2e08-4ed6-b737-d49b69fecf81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='生日特惠'])[2]/following::a[2]</value>
      <webElementGuid>d65e7b3f-d89d-4b27-9c18-2e34786a8d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='訂單紀錄'])[2]/preceding::a[1]</value>
      <webElementGuid>b2778512-daa1-440a-a54b-0a4a204ccce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='追蹤清單'])[1]/preceding::a[2]</value>
      <webElementGuid>97c8aba5-b67d-451d-902d-4125d4c48906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/my-account')])[4]</value>
      <webElementGuid>285bce36-955e-40ed-8603-3d7699ec8e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/div/ul/li[2]/a</value>
      <webElementGuid>53a22db2-2ae0-4432-9bf3-82cda4232af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/my-account' and (text() = '我的帳戶' or . = '我的帳戶')]</value>
      <webElementGuid>7615d381-e22a-4bb3-8b62-ada164b75dfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
