<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_owing-balance_paybutton</name>
   <tag></tag>
   <elementGuidId>d5c7b434-df45-4930-8289-496bb867df66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.a-button.flex.justify-center.w-120.h-30</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/div/div/div[3]/section/div[2]/div/ul/li[6]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>22edd58b-7fcb-43c1-8d22-b9c6ec690302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button flex justify-center w-120 h-30</value>
      <webElementGuid>be020634-86f2-4a2a-90cf-c2734837c907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/my-account/owing-balance?orderNumber=124084574</value>
      <webElementGuid>7155701e-f3fe-46a0-9124-0e69fe404397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    付款
    </value>
      <webElementGuid>d4d2ee89-dff1-48a7-bd6f-ad73b30c0bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[1]/div[@class=&quot;o-widthControl mx-auto w-full max-w-full to-md:px-10 md:max-w-contain md:py-40&quot;]/div[3]/section[@class=&quot;o-po&quot;]/div[@class=&quot;o-po__orders -list&quot;]/div[@class=&quot;m-po__wrapper&quot;]/ul[@class=&quot;m-po__header&quot;]/li[@class=&quot;m-po__track -col-md-2&quot;]/div[@class=&quot;m-po__track-inner -payBtn&quot;]/a[@class=&quot;a-button flex justify-center w-120 h-30&quot;]</value>
      <webElementGuid>37265bf4-bced-4d10-978f-c5381eb943eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/div/div[3]/section/div[2]/div/ul/li[6]/div/a</value>
      <webElementGuid>883869fe-2173-4fd2-bdca-7bb9745d7cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'付款')])[4]</value>
      <webElementGuid>8ba29cdc-62d5-4383-b4ef-bba2a4d48996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NT$2,470'])[1]/following::a[1]</value>
      <webElementGuid>abe3d654-fc33-4394-8602-c4014c814e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='優惠總額節省:'])[1]/following::a[1]</value>
      <webElementGuid>b7f98103-a850-4bed-a075-e4e6dfd4a94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⋮'])[1]/preceding::a[1]</value>
      <webElementGuid>573b35ef-d0b9-40f9-ab09-ead0da6bd201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='列印我的收據'])[1]/preceding::a[1]</value>
      <webElementGuid>5b8ee642-4408-4133-825d-f2ef5f890d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='付款']/parent::*</value>
      <webElementGuid>112d07c3-0658-4108-9940-bace00e2fa2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/my-account/owing-balance?orderNumber=124084574')]</value>
      <webElementGuid>fb8b1c63-89e5-451b-b5dc-fad5762e7b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/a</value>
      <webElementGuid>555d480a-291a-4200-83cf-9e95c2f35ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/my-account/owing-balance?orderNumber=124084574' and (text() = '
    付款
    ' or . = '
    付款
    ')]</value>
      <webElementGuid>81c70956-b4c2-478a-8ff9-e60ce24b2ea0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
