<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_skin care</name>
   <tag></tag>
   <elementGuidId>ed2c0d1a-bde6-4519-af06-09f138da2463</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lvlD0C4155D432D41CCA7A960D72FBA386B > li.m-navMenu__item.-lvl2.Both > a.m-navMenu__item-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='lvlD0C4155D432D41CCA7A960D72FBA386B']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc213739-21da-4343-b368-a95f4f0b259b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/productstore/beauty/premium-skin-care</value>
      <webElementGuid>e8b10743-b5fd-4d96-b854-310b6e24c0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e0654434-b6ff-4843-bb1d-852c571d08a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>57abb64b-c579-49fc-8b51-7b96867682ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8ab03d33-91bc-4e86-bf41-dafaff534844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-navMenu__item-btn</value>
      <webElementGuid>67004637-6b3a-4c00-a842-b86cddfa9ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b7b4bfa-ad97-4ed6-afe4-15b741240713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>肌膚保養系列 </value>
      <webElementGuid>f31fd5bb-197d-44b0-8cbb-ff9cbec26769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lvlD0C4155D432D41CCA7A960D72FBA386B&quot;)/li[@class=&quot;m-navMenu__item -lvl2 Both&quot;]/a[@class=&quot;m-navMenu__item-btn&quot;]</value>
      <webElementGuid>718cb6e4-bee1-483e-b5e2-aacf9d515bdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='lvlD0C4155D432D41CCA7A960D72FBA386B']/li[3]/a</value>
      <webElementGuid>07b820a0-8415-4e06-b636-d7442c564a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'肌膚保養系列')]</value>
      <webElementGuid>984fde78-0150-4250-b860-ad5a04cde131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='美妝保養'])[3]/following::a[1]</value>
      <webElementGuid>41c6f869-0006-4e04-8d85-34e6cf7a4614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='回上一頁'])[6]/following::a[2]</value>
      <webElementGuid>ff0060cc-faf4-433f-b56c-c8eca288d544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='自然美妝系列'])[1]/preceding::a[1]</value>
      <webElementGuid>c416fe6f-454b-4154-8b58-1204bd17cf8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='美髮沙龍系列'])[1]/preceding::a[2]</value>
      <webElementGuid>a1c82c65-63df-46ac-b23d-60c245bd0ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='肌膚保養系列']/parent::*</value>
      <webElementGuid>ecd45e5f-3388-4d60-85ef-9bd47ffad140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/productstore/beauty/premium-skin-care')]</value>
      <webElementGuid>18d65b11-023f-43ff-bccd-df04fa130a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/ul/li[3]/a</value>
      <webElementGuid>8adb2196-13e2-4979-b777-1bc41960df8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/productstore/beauty/premium-skin-care' and (text() = '肌膚保養系列 ' or . = '肌膚保養系列 ')]</value>
      <webElementGuid>e6655a2c-0d8a-4b65-9e49-c36ad2849c76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
