<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_special offer</name>
   <tag></tag>
   <elementGuidId>d2aa29a0-a3d6-49f0-9d53-17bded155544</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lvlB2A4B89E39114FE3BF5E5E5E71A42929 > li.m-navMenu__list.-title > a.block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='lvlB2A4B89E39114FE3BF5E5E5E71A42929']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6ddf0f1a-3b66-4281-8152-84aaa398a490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/productstore/extra-savings</value>
      <webElementGuid>c2ce8f84-bc5e-4526-b2d0-92e68072f500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block</value>
      <webElementGuid>39743839-e6b0-42f9-adb7-eda0420004c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>特惠專區</value>
      <webElementGuid>ee39f244-ed45-4283-9946-6488cd880e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lvlB2A4B89E39114FE3BF5E5E5E71A42929&quot;)/li[@class=&quot;m-navMenu__list -title&quot;]/a[@class=&quot;block&quot;]</value>
      <webElementGuid>ad00f1f3-4047-4113-ba19-7df1a9b3b9ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='lvlB2A4B89E39114FE3BF5E5E5E71A42929']/li[2]/a</value>
      <webElementGuid>51550cea-b6b2-4146-bb73-f70343be317f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'特惠專區')])[2]</value>
      <webElementGuid>857e31e5-8a8d-4789-81cc-ae96c1df09fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='回上一頁'])[7]/following::a[1]</value>
      <webElementGuid>e693c32c-1e8d-421e-95be-297b516a4047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新品'])[2]/following::a[2]</value>
      <webElementGuid>3953206d-09af-459e-8ba6-dd22945055f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='本月特惠'])[1]/preceding::a[1]</value>
      <webElementGuid>e02abe92-5f02-48b8-a899-92fa5cc3f06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='滿40點特惠'])[1]/preceding::a[2]</value>
      <webElementGuid>3d9d7c59-d2a6-49d0-9396-f9322a45f810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/productstore/extra-savings')]</value>
      <webElementGuid>9885c61c-18ed-433d-b5a9-530619e175cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]/div/ul/li[2]/a</value>
      <webElementGuid>23772c7a-7641-40c9-b7f0-e3246c9bd1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/productstore/extra-savings' and (text() = '特惠專區' or . = '特惠專區')]</value>
      <webElementGuid>96367dec-ee0a-4c28-b0e8-73a7690bba97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
