<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_vip</name>
   <tag></tag>
   <elementGuidId>e1cf9177-f8dc-48d7-ab85-f326a9147eb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='lvlB2A4B89E39114FE3BF5E5E5E71A42929']/li[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4bbb0138-530c-4dca-a6ca-0bf1a0792ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/productstore/extra-savings/lvip-promotions-lifetimevipgold</value>
      <webElementGuid>db0a524c-e639-480e-ad75-453c71892c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c7c0b983-035e-49ed-91e9-7520ee0f2db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>4f838b3c-cabb-4733-8f70-7609ce58280c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fc42ea4e-c350-4c5e-b77b-b59a31f44964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-navMenu__item-btn</value>
      <webElementGuid>06bd5681-5a6e-4de3-8746-7879987b8f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d57abe9a-3c09-4a7b-8b4e-8140b91e8164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>尊榮/永恆卡獨家特惠 </value>
      <webElementGuid>40aabe8f-1261-4b08-8bae-c1a47c310a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lvlB2A4B89E39114FE3BF5E5E5E71A42929&quot;)/li[@class=&quot;m-navMenu__item -lvl2&quot;]/a[@class=&quot;m-navMenu__item-btn&quot;]</value>
      <webElementGuid>2dd5a249-0d95-4f6d-b0d9-da886948e3d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='lvlB2A4B89E39114FE3BF5E5E5E71A42929']/li[7]/a</value>
      <webElementGuid>c409974c-5e2d-4bc2-b56a-cea64c599ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'尊榮/永恆卡獨家特惠')]</value>
      <webElementGuid>7df2ff9b-8f81-4875-a786-48ae25fd5ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='絕版商品'])[3]/following::a[1]</value>
      <webElementGuid>02fa7964-49b4-4cb6-9eeb-0a3ba41a9dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='套組推薦'])[1]/following::a[2]</value>
      <webElementGuid>5119323f-21bc-4417-9d88-d1adc41b20eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='生日特惠'])[1]/preceding::a[1]</value>
      <webElementGuid>39aa0669-8beb-4527-806f-c493abcc43d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我的帳戶'])[2]/preceding::a[2]</value>
      <webElementGuid>190b88e5-6050-4905-b5d3-91a70d7818dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='尊榮/永恆卡獨家特惠']/parent::*</value>
      <webElementGuid>a132d411-7a05-425d-8d1a-c5768df8e656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/productstore/extra-savings/lvip-promotions-lifetimevipgold')]</value>
      <webElementGuid>711a2c5c-7a47-49be-9301-a3227d4b4dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]/div/ul/li[7]/a</value>
      <webElementGuid>2d77128a-3ed2-431c-bd1d-97c95259bef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/productstore/extra-savings/lvip-promotions-lifetimevipgold' and (text() = '尊榮/永恆卡獨家特惠 ' or . = '尊榮/永恆卡獨家特惠 ')]</value>
      <webElementGuid>bc7a4cd1-f1b7-46ba-a70b-8228c932dc61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
