<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_7911-sku2</name>
   <tag></tag>
   <elementGuidId>c26bb66b-ca15-4bfc-b009-4b59be7bf275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.m-refinerImage__img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/div[2]/div/div/ul/li[2]/button/div[1]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2494e590-7a92-475d-9660-9ea221bd7b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//cdnsc1.melaleuca.com/cdn-cgi/image/width=64height=64,quality=85/global/products/60138h-01-zhtw.png</value>
      <webElementGuid>cd436736-e9f6-4f01-8f09-81cffb86d2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>柳橙口味</value>
      <webElementGuid>241d97e1-bc23-4248-8b2f-af584ecb2834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-refinerImage__img</value>
      <webElementGuid>90d70ac3-6244-43d0-976d-2d35c5c5a6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__VID__564__MelaId_lsogrevx__contentId&quot;)/div[@class=&quot;o-configuratorAcc__content&quot;]/div[@class=&quot;ps&quot;]/ul[@class=&quot;o-configuratorAcc__list&quot;]/li[@class=&quot;o-configuratorAcc__item&quot;]/button[@class=&quot;m-refinerImage&quot;]/div[@class=&quot;m-refinerImage__media&quot;]/img[@class=&quot;m-refinerImage__img&quot;]</value>
      <webElementGuid>9c5c844a-e28b-434b-bc29-35f172c4e913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__VID__564__MelaId_lsogrevx__contentId']/div/div/ul/li/button/div/img</value>
      <webElementGuid>cfda9815-cb89-45a5-b069-d7d3efcb773c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='柳橙口味']</value>
      <webElementGuid>8c1d0ede-d3c5-4004-a380-0cda0bbc2cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/img</value>
      <webElementGuid>5b5cad03-b142-40ba-9a15-33429d2fd880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//cdnsc1.melaleuca.com/cdn-cgi/image/width=64height=64,quality=85/global/products/60138h-01-zhtw.png' and @alt = '柳橙口味']</value>
      <webElementGuid>cb78d6d9-63f4-4721-b1d0-692e8d8abbde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
