<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_7911-sku2</name>
   <tag></tag>
   <elementGuidId>c26bb66b-ca15-4bfc-b009-4b59be7bf275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.m-refinerImage__img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/div[2]/div/div/ul/li[2]/button/div[1]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ed50438b-8ffd-464a-a81c-7df1ac51ab56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//cdnsc1.melaleuca.com/cdn-cgi/image/width=64height=64,quality=85/global/products/60138h-01-zhtw.png</value>
      <webElementGuid>0cc7c406-040d-4735-9fd6-d332892139d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>柳橙口味</value>
      <webElementGuid>dde68aaf-4751-462d-9d72-c908b3d8cfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-refinerImage__img</value>
      <webElementGuid>123c70cc-504c-4b69-99fb-e9e3d8de30c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__VID__564__MelaId_lsogrevx__contentId&quot;)/div[@class=&quot;o-configuratorAcc__content&quot;]/div[@class=&quot;ps&quot;]/ul[@class=&quot;o-configuratorAcc__list&quot;]/li[@class=&quot;o-configuratorAcc__item&quot;]/button[@class=&quot;m-refinerImage&quot;]/div[@class=&quot;m-refinerImage__media&quot;]/img[@class=&quot;m-refinerImage__img&quot;]</value>
      <webElementGuid>36e7405e-611c-4c21-8777-150ccf3c2525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__VID__564__MelaId_lsogrevx__contentId']/div/div/ul/li/button/div/img</value>
      <webElementGuid>d48551de-20de-4641-901e-68db4709e068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='柳橙口味']</value>
      <webElementGuid>696ec8a2-74f0-461b-af0e-de35e63c715d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/img</value>
      <webElementGuid>54db39dc-f38c-4d23-be2d-ba76175e06dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//cdnsc1.melaleuca.com/cdn-cgi/image/width=64height=64,quality=85/global/products/60138h-01-zhtw.png' and @alt = '柳橙口味']</value>
      <webElementGuid>c10239a1-ad59-4e88-af24-a43fac7860ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
