<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_refinerImage_img1</name>
   <tag></tag>
   <elementGuidId>f8af9b04-a814-4420-ac99-fcb39e0c635f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.m-refinerImage__img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div/div/div[2]/div/div[2]/div[2]/div[1]/div/div[2]/div/div/ul/li[1]/button/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>adc1f7d8-af78-4666-83af-5922168d51bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//cdnsc1.melaleuca.com/cdn-cgi/image/width=64height=64,quality=85/global/products/5509h-01-zhtw.png</value>
      <webElementGuid>2d7fd0a8-0e7b-4cda-8010-823c2e2d3d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>水潤柔順洗髮乳-摩洛哥堅果油&amp;椰子</value>
      <webElementGuid>a6b9afe5-1f2e-47ea-b2de-13b255333a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-refinerImage__img</value>
      <webElementGuid>d3b52186-563b-489d-bce9-311555bf9fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__VID__814__MelaId_lsogsf8c__contentId&quot;)/div[@class=&quot;o-configuratorAcc__content&quot;]/div[@class=&quot;ps ps--active-y&quot;]/ul[@class=&quot;o-configuratorAcc__list&quot;]/li[@class=&quot;o-configuratorAcc__item&quot;]/button[@class=&quot;m-refinerImage&quot;]/div[@class=&quot;m-refinerImage__media&quot;]/img[@class=&quot;m-refinerImage__img&quot;]</value>
      <webElementGuid>0e5b6968-6265-4930-8210-6684e8fd2f58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__VID__814__MelaId_lsogsf8c__contentId']/div/div/ul/li/button/div/img</value>
      <webElementGuid>9e844e16-cee6-4c54-90fe-532f4465e1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='水潤柔順洗髮乳-摩洛哥堅果油&amp;椰子']</value>
      <webElementGuid>3cb67bcd-6686-4c30-a457-891d48d72df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/img</value>
      <webElementGuid>23eeb7d3-f3c5-40ff-b001-f176d9f2bb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//cdnsc1.melaleuca.com/cdn-cgi/image/width=64height=64,quality=85/global/products/5509h-01-zhtw.png' and @alt = '水潤柔順洗髮乳-摩洛哥堅果油&amp;椰子']</value>
      <webElementGuid>ab1cb128-4f11-4836-88a6-0604d23a6ab7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
