<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_delete item3</name>
   <tag></tag>
   <elementGuidId>024182f2-2fcc-4378-bf25-5beded738b53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Close Box&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='isRemovedButton4863']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>47664924-221e-4e3a-8c50-e637305f0442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//cdnsc1.melaleuca.com/na/images/header/clear2x.png</value>
      <webElementGuid>c5a5aa77-e164-4f7f-bf3b-8f265e5ff7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Close Box</value>
      <webElementGuid>054ce474-2a7e-48a0-86df-db62fd70bd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e3561fce-2cdc-432b-a640-9a5c2c60dc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isRemovedButton1216&quot;)/img[1]</value>
      <webElementGuid>c73bb532-035a-4d66-80b2-e4944fc9afb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='isRemovedButton4863]/img</value>
      <webElementGuid>88c860d5-7ecf-428e-9d77-e428049dbed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Close Box']</value>
      <webElementGuid>097dca32-82d2-4b97-b80f-420bed238044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button/img</value>
      <webElementGuid>9a01855f-3116-4322-9198-9d02708d8b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//cdnsc1.melaleuca.com/na/images/header/clear2x.png' and @alt = 'Close Box']</value>
      <webElementGuid>13e0e620-b4d9-421f-bab3-e4490324ca99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
