<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_identificationString</name>
   <tag></tag>
   <elementGuidId>42b2a6bd-736a-4388-8219-de741324a6ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__VID__60__MelaId_lqykuo9k__emailPhoneInputId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/main/div[1]/div/div/div[1]/div[2]/div[1]/div[1]/div/div/form/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ad43ca1-1eb3-4395-8a3f-d3112250fe98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__VID__60__MelaId_lqykuo9k__emailPhoneInputId</value>
      <webElementGuid>305853d2-05d5-46a5-bead-31ff20e19e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd034dba-6ea8-461b-be88-05c0ae0cd841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identificationString</value>
      <webElementGuid>d761b655-81e8-4e31-b917-c0ad31baccf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>db972582-25a0-4b9a-abff-e59aaf5df2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input -text</value>
      <webElementGuid>cee28a9b-d108-48fa-9388-162901232378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__VID__60__MelaId_lqykuo9k__emailPhoneInputId&quot;)</value>
      <webElementGuid>44d26a3b-5df3-450b-8cfc-ad4ffe121073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__VID__60__MelaId_lqykuo9k__emailPhoneInputId']</value>
      <webElementGuid>01faeb89-dbd6-43c9-bd9d-1963a1d693ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/div/div/div/div[2]/div/div/div/div/form/div/div/input</value>
      <webElementGuid>50b51e60-3001-4e6d-9fe4-6f0a408abe45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>a3e2a5f1-8373-4824-aa31-63604df2fccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '__VID__60__MelaId_lqykuo9k__emailPhoneInputId' and @type = 'text' and @name = 'identificationString']</value>
      <webElementGuid>90038b71-476a-4ada-aec6-126866399cf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
