<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cvv code</name>
   <tag></tag>
   <elementGuidId>1f66b0a2-55f4-40b7-8bb7-81f0e409b658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cvvCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cvvCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7495d9a-94b3-4e91-8b23-9401d6f07460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cvvCode</value>
      <webElementGuid>7ce6e7d3-7029-4a3a-88bf-70546b9ff9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvvCode</value>
      <webElementGuid>4b611cdb-06b7-4ac1-b320-8aa7ed0a3b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b9b130a1-116f-40b0-ad99-b2178450e2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9b7c6f20-6301-40c8-ae2d-fedabbee6f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1c0d601-a34d-4dc1-94fd-3021cd4569ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input bg-clear p-checkout__input -text</value>
      <webElementGuid>b036ca86-3728-40df-b526-f69f6898ea02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8862fb93-ba1b-4f4e-8afc-d5ddce88ded0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvvCode&quot;)</value>
      <webElementGuid>10e07d49-4e4d-4d47-b858-aeba141e88b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cvvCode']</value>
      <webElementGuid>63d6046a-eb6a-41bb-ba7b-9ca15a54fe5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/div/div/div[3]/div/div[4]/div[3]/div/div/input</value>
      <webElementGuid>a05d90a2-7e67-4569-aa20-41e00803453f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>810da86c-916d-4d85-b9a4-cb3afbca8731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cvvCode' and @name = 'cvvCode' and @type = 'text']</value>
      <webElementGuid>fc661c8d-0f39-4299-ae77-905d332a94cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
