<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_now lsd</name>
   <tag></tag>
   <elementGuidId>cec41bb9-6783-478f-bb2f-355383580132</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/main/div[1]/div/div/div[4]/div[1]/div[6]/div/p[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>44dbdfc3-5e64-4e73-bd52-1ea52e567118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-checkoutLSD__amount</value>
      <webElementGuid>7f03bd23-61fb-4ce8-a1c4-ef67b09f8ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NT$165</value>
      <webElementGuid>81651315-5562-43f7-80f0-26e4ec954e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;bg-gray-25&quot;]/div[@class=&quot;p-checkout&quot;]/div[@class=&quot;p-checkout__wrapper&quot;]/div[@class=&quot;p-checkout__content&quot;]/div[@class=&quot;p-checkout__main&quot;]/div[8]/div[@class=&quot;m-checkoutLSD&quot;]/p[@class=&quot;m-checkoutLSD__text&quot;]/span[@class=&quot;m-checkoutLSD__amount&quot;]</value>
      <webElementGuid>76391782-ce44-47ff-b830-5ef06cb02316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/div/div/div[3]/div/div[8]/div/p[2]/span</value>
      <webElementGuid>c32857b9-3096-498a-946c-6fab9ee60389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NT$165'])[1]/following::span[1]</value>
      <webElementGuid>088323d3-322c-4b76-83cc-de1ccc0c09c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='消費回饋'])[2]/following::span[2]</value>
      <webElementGuid>973865ae-6264-43be-b2ec-0ad3c805ceda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='結帳明細'])[1]/preceding::span[1]</value>
      <webElementGuid>11a117bb-5017-4e3f-bed7-64ffbb7faf3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='產品小計'])[1]/preceding::span[2]</value>
      <webElementGuid>d21a9229-64d7-470b-9d5f-8245f2267a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/span</value>
      <webElementGuid>4e80dc35-398c-4628-a9f0-84733f32a3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'NT$165' or . = 'NT$165')]</value>
      <webElementGuid>4272a231-3942-4c38-a770-979bb456ac2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
