<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_shopping_cart sku3</name>
   <tag></tag>
   <elementGuidId>5147abad-579e-48cb-b67c-87f3a05eaea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/main/div[1]/div[2]/div[3]/div[2]/div[1]/div/div[2]/div/div/div/div/div/div[1]/div[1]/ul/li[28]/article/div[3]/div/button/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>66eae199-c28f-4ba4-a831-1593ff0d3012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d0decc8-3570-4146-b1ca-ea4998ac6232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon material-icons -inherit</value>
      <webElementGuid>01b302f1-a6da-4467-a950-02bfcbda464b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>shopping_cart</value>
      <webElementGuid>3893a848-06b0-4b24-959f-16417bd85f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__VID__110__MelaId_lsogroa7__contentId&quot;)/div[@class=&quot;o-cartAccordion__content&quot;]/div[@class=&quot;ps ps--active-y&quot;]/div[@class=&quot;o-cartAccordion__scroll&quot;]/ul[@class=&quot;o-recentlyPurchased&quot;]/li[@class=&quot;o-recentlyPurchased__item&quot;]/article[@class=&quot;m-recentProduct -buyAgain&quot;]/div[@class=&quot;m-recentProduct__add&quot;]/button[@class=&quot;m-recentProduct__cart&quot;]/span[@class=&quot;a-icon material-icons -inherit&quot;]</value>
      <webElementGuid>7edc7831-00d3-4511-a3db-8a554c364c8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__VID__110__MelaId_lsogroa7__contentId']/div/div/div/ul/li/article/div[3]/button/span[2]</value>
      <webElementGuid>7e1f36a3-b466-4fac-b500-d6628990914c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NT$219'])[1]/following::span[2]</value>
      <webElementGuid>4f92fbaa-7f50-45c3-a145-907c16bfe47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='活力隨行杯'])[1]/following::span[2]</value>
      <webElementGuid>f5c60e90-dbff-4adb-93ef-fe01c539be28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='美樂家活力核酸機能果凍_四盒組'])[1]/preceding::span[1]</value>
      <webElementGuid>8e8ed0e3-b397-4d8a-bd8c-1d6c9e54fab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NT$3,590'])[1]/preceding::span[1]</value>
      <webElementGuid>ec8162c2-6648-4082-ba35-2cf990b4774d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span[2]</value>
      <webElementGuid>286b03ae-e23b-4956-9191-af531a01d8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'shopping_cart' or . = 'shopping_cart')]</value>
      <webElementGuid>3a50093b-7346-4ecf-aaa9-cf029dfe8102</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
