<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_keyboard_arrow_down1</name>
   <tag></tag>
   <elementGuidId>9488e440-3e70-4e60-a81c-0f39d3252bde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-icon.material-icons.-inherit.-transition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/main/div[1]/div[2]/div[3]/div[2]/div[1]/div/div[1]/div/div/div/h2/button/span[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a4b6c743-9a2c-47c3-9ac6-439b3311d05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1b714e6-7620-4a60-a749-5add24adc3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon material-icons -inherit -transition</value>
      <webElementGuid>75505bfe-dc5e-47ac-881f-909ffcf80846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    keyboard_arrow_down
                </value>
      <webElementGuid>a3aa56da-c946-4284-b14c-bb644120e8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__VID__110__MelaId_lsogroa7__toggleId&quot;)/span[@class=&quot;text-2xl leading-none&quot;]/span[@class=&quot;a-icon material-icons -inherit -transition&quot;]</value>
      <webElementGuid>455695ed-d8ff-44ce-8d78-3bc492d59128</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='__VID__110__MelaId_lsogroa7__toggleId']/span[3]/span</value>
      <webElementGuid>e9498ec5-6649-4bc6-8045-5ed0aae9e734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='曾買過品項'])[1]/following::span[4]</value>
      <webElementGuid>9ee72ed4-bd88-49f3-ad12-6d2e21382488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='如何獲得'])[2]/following::span[6]</value>
      <webElementGuid>ebbe38ee-0cef-4b6a-9fdb-df045348f12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='活力隨行杯'])[1]/preceding::span[1]</value>
      <webElementGuid>eaa55105-9cba-46a1-97a8-a9b8952c85e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NT$219'])[1]/preceding::span[1]</value>
      <webElementGuid>beaa3553-97cc-4915-9602-926927834f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='keyboard_arrow_down']/parent::*</value>
      <webElementGuid>a02ccfb6-8bd2-4875-a7d4-694f8744ea5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[3]/span</value>
      <webElementGuid>73a7631d-c1b9-4cc6-aded-e0f26835aa6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                    keyboard_arrow_down
                ' or . = '
                    keyboard_arrow_down
                ')]</value>
      <webElementGuid>ca156c2e-9fe0-4d0e-8440-2541978f0ac6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
