<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_Inbound_Account</name>
   <tag></tag>
   <elementGuidId>e2300653-f9b5-4c60-952d-b6edd84bc7d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txt_Inbound_Account&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txt_Inbound_Account']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d895918-4e56-4c65-8617-5935c53bcc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern</value>
      <webElementGuid>b57fd98a-8a01-4882-a71d-779cd339292b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_Inbound_Account</value>
      <webElementGuid>53ffc870-8ead-4bd6-af7f-e0319f0f80d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>paymethod.AccountNumber</value>
      <webElementGuid>380cd697-3b8d-4168-a395-111371ce6572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>帳戶號碼</value>
      <webElementGuid>6d8a3887-5d47-4234-a59b-836b09449cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>08b3773b-70dc-483f-b4b2-70f699bf8c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>ValidateAccountNumberAndCardIssuer()</value>
      <webElementGuid>94401fea-89d8-45d1-b091-b5e929fea807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isDisablePaymethodInformation()</value>
      <webElementGuid>7dd0ddfc-4bcc-4b16-af87-f4186e648c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseVisa&quot;)/div[@class=&quot;paymethodGroup ng-pristine ng-valid ng-valid-pattern ng-valid-required&quot;]/div[@class=&quot;form-group col-md-4 ng-pristine ng-valid ng-valid-pattern&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern&quot;]</value>
      <webElementGuid>f75e9241-235d-4605-b267-c9182252a195</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txt_Inbound_Account']</value>
      <webElementGuid>53d105d7-727f-4289-93ae-1bee78ef970e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseVisa']/div/div/input</value>
      <webElementGuid>4291ca85-9b27-4915-b0fb-27144d247c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>54318515-7ffa-4c50-9c29-06baaf3ddc8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txt_Inbound_Account' and @placeholder = '帳戶號碼']</value>
      <webElementGuid>107fa013-f037-49d8-9150-2a15f017af78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
