<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_zh-TWzh-HK (1)</name>
   <tag></tag>
   <elementGuidId>a8dec8fe-b68b-4d32-a0ac-10b0b21be52f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-control.ng-pristine.ng-untouched.ng-valid.ng-not-empty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CMA']/div/div/culture-select/fieldset/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3922e25c-46b2-438c-87ef-9b3adc71b1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>91aa9d58-7943-4e64-a157-27c6ec63a46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>selectedCulture</value>
      <webElementGuid>22faeed2-3c6c-4a9f-89ad-bd05a7fe144d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>ChangeCulture()</value>
      <webElementGuid>13def57b-05c7-4064-97fc-9886941c0f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                zh-TWzh-HK
            </value>
      <webElementGuid>cb7bcb08-481e-4a8d-9954-bf444fcbcf65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CMA&quot;)/div[1]/div[@class=&quot;CMA zh-TW ng-scope&quot;]/culture-select[@class=&quot;ng-isolate-scope&quot;]/fieldset[@class=&quot;col-md-12 group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-md-2 clearBoth&quot;]/select[@class=&quot;form-control ng-pristine ng-untouched ng-valid ng-not-empty&quot;]</value>
      <webElementGuid>519766ef-b358-4b94-bbb6-8d5380984ffb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CMA']/div/div/culture-select/fieldset/div/div/select</value>
      <webElementGuid>89a7d57c-eef3-4d1d-9c65-d4fef37d2b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='選擇文化'])[1]/following::select[1]</value>
      <webElementGuid>8cccfbd9-08a7-4368-83f0-035ccab8354c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入會日期'])[1]/preceding::select[1]</value>
      <webElementGuid>f45ff9ca-1048-42eb-928a-19cc40506eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='測試顧客'])[1]/preceding::select[1]</value>
      <webElementGuid>270d3686-4c1b-4b9f-8de4-c5168d802f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2f115d7c-2382-423a-8bd1-c709024ad166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '
                zh-TWzh-HK
            ' or . = '
                zh-TWzh-HK
            ')]</value>
      <webElementGuid>cd515e36-4563-4c47-8105-c2778b28bcb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
