<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_add</name>
   <tag></tag>
   <elementGuidId>fa61a103-d3f6-4657-bd1d-d611186f6823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/div/div[2]/div[3]/div/div[3]/div/div/div[2]/div/div/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e0bed0a2-2f73-4c3b-ad9a-872927f94855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>25a64a86-685a-40b5-bfed-aafe00793635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon material-icons -inherit</value>
      <webElementGuid>4c691782-b955-4df1-8fc5-2264a3f246eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>c0c7886b-b508-4596-987a-5c468fb88404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;p-cart&quot;]/div[@class=&quot;p-cart__container&quot;]/div[@class=&quot;p-cart__content&quot;]/div[@class=&quot;p-cart__main&quot;]/div[@class=&quot;o-cartItem&quot;]/div[@class=&quot;o-cartItem__row -product&quot;]/div[@class=&quot;o-cartItem__container&quot;]/div[@class=&quot;o-cartItem__controls&quot;]/div[@class=&quot;o-cartItem__quantity&quot;]/div[@class=&quot;a-quantity&quot;]/button[@class=&quot;a-quantity__btn&quot;]/span[@class=&quot;a-icon material-icons -inherit&quot;]</value>
      <webElementGuid>f7887a7b-dbcb-4d90-ab85-93a0d36088b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/div[2]/div[3]/div/div[3]/div/div/div[2]/div/div/button[2]/span</value>
      <webElementGuid>6fad19bf-e63c-4bf3-b72e-659e000d4810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='| $26.40 Savings'])[1]/following::span[2]</value>
      <webElementGuid>f3c87d63-4efc-4091-ab36-4cb472046279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$163.50'])[1]/preceding::span[1]</value>
      <webElementGuid>4bb81e02-1ed0-4bfe-9edc-49e94106a783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::span[3]</value>
      <webElementGuid>9ebfe48b-700e-4eda-a5bc-6be4d24060f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='add']/parent::*</value>
      <webElementGuid>01ef7906-2b3a-44e9-af81-b940ce919ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button[2]/span</value>
      <webElementGuid>6add5ebc-7905-4895-9bed-11c11e1c9952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'add' or . = 'add')]</value>
      <webElementGuid>c422b891-9540-450c-8c54-b4278b2e389d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
