<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>fba6b263-0ee7-4804-b5ee-149927ebc3b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.m-po__third-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='0']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3d7e1ec4-a6d8-491f-a1e2-64dcb7d1b9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/receipt?orderId=12529908</value>
      <webElementGuid>c0ad1a6c-d00f-4144-ae06-eafc247f3be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>See Full Order Receipt for order number 12529908</value>
      <webElementGuid>8880600d-acc1-4096-ae92-a4510fcabe40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-po__third-title</value>
      <webElementGuid>117dc390-fb41-4ff2-9daa-6a1cb469b1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>注文明細を見る
</value>
      <webElementGuid>eff04e47-ad98-45d3-9dbd-c4743d6bc547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0&quot;)/a[@class=&quot;m-po__third-title&quot;]</value>
      <webElementGuid>cf0831f1-aaf1-4eaf-868c-0969cfd36697</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='0']/a</value>
      <webElementGuid>661609ae-5ef4-4933-806c-17cf60666bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'注文明細を見る')]</value>
      <webElementGuid>09c2323c-4409-4628-8118-a6b145385fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='処理中'])[1]/following::a[1]</value>
      <webElementGuid>13d7cec3-77ca-4ac3-b1eb-9c9171cd76c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='注文をカートに入れる'])[1]/following::a[1]</value>
      <webElementGuid>79ebd1dd-46ae-45ad-87d9-209f9f7899e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='横浜市港北区, 神奈川県 2220033'])[1]/preceding::a[1]</value>
      <webElementGuid>2a79ae78-db3e-4214-a9a5-521c02ff9461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='注文明細を見る']/parent::*</value>
      <webElementGuid>90e47fa6-f958-41e8-8a43-8ea4af0219a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/receipt?orderId=12529908')]</value>
      <webElementGuid>1b6923cf-1ca5-487c-8a2a-52e349ac4ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/a</value>
      <webElementGuid>ea1bbe80-401e-4ff1-afd2-e2524d2a4dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/receipt?orderId=12529908' and (text() = '注文明細を見る
' or . = '注文明細を見る
')]</value>
      <webElementGuid>b6607d75-d696-47ec-affd-baf777ccb971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
