<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manage Payment Methods</name>
   <tag></tag>
   <elementGuidId>a7406ad5-8ced-4f7c-9d67-8205cb2e9a83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__VID__58__MelaId_llm5brm0__accordionId']/div/div[3]/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7a2aeb2-865e-4bf1-9762-27d2e9ded256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/my-account/payments-and-addresses</value>
      <webElementGuid>639e8fd4-b0cb-409e-9e80-08adf339b5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-green uppercase underline text-sm</value>
      <webElementGuid>31b676c4-9e46-497c-9576-5cc77f91c980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Payment Methods</value>
      <webElementGuid>4d573002-2cb9-4138-a961-41f94dfdc9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__VID__58__MelaId_llm5brm0__accordionId&quot;)/div[@class=&quot;o-checkoutAccordion__content&quot;]/div[@class=&quot;o-checkoutAccordion__action&quot;]/div[@class=&quot;flex flex-col md:flex-row justify-start md:justify-between items-start md:items-center&quot;]/a[@class=&quot;text-green uppercase underline text-sm&quot;]</value>
      <webElementGuid>74d313c2-905a-434a-9724-5aa49bba5c90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__VID__58__MelaId_llm5brm0__accordionId']/div/div[3]/div/a[2]</value>
      <webElementGuid>d85256b9-2c85-4e5b-b60a-3573959c23b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Manage Payment Methods')]</value>
      <webElementGuid>04f7641d-7d8b-4c35-8f14-0d3fe3589f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ ADD NEW PAYMENT METHOD'])[1]/following::a[1]</value>
      <webElementGuid>0517a267-bf37-4f92-a655-3af8b17a3cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security code'])[1]/preceding::a[1]</value>
      <webElementGuid>ff0732d4-8c0d-46ee-808f-5d754d73c0ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CVV'])[1]/preceding::a[1]</value>
      <webElementGuid>2a5a7004-810e-44e0-90f7-506ed55a7b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage Payment Methods']/parent::*</value>
      <webElementGuid>76e6d27d-450c-4f13-99e4-bd129c6752a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/my-account/payments-and-addresses')])[8]</value>
      <webElementGuid>c3733c55-7574-4f51-a802-3af5907fae6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a[2]</value>
      <webElementGuid>df1d4548-9702-44db-8a16-c4c607cb8e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/my-account/payments-and-addresses' and (text() = 'Manage Payment Methods' or . = 'Manage Payment Methods')]</value>
      <webElementGuid>8ffe3edd-5706-44b6-8c23-96b6e8b727ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
