<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Price_o-savedLaterCarousel__removeIcon</name>
   <tag></tag>
   <elementGuidId>b8e5fddb-0323-4176-bac9-d6a887bc168e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carousel-3b7fb337-cf94-42e8-9ae3-2a6564603451']/div/div/div[2]/div/div/article/div[2]/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1e92e94f-c48d-4bae-9b09-ab46c6230de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//cdnsc1.melaleuca.com/na/images/common/trash.png</value>
      <webElementGuid>ce5298ca-ed96-4942-9937-d2258f5d40e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36c764f9-f51c-4ccc-b323-b6e24efb10d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-savedLaterCarousel__removeIcon</value>
      <webElementGuid>07450c17-8de8-4bf1-ba47-f29df3dbc743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carousel-3b7fb337-cf94-42e8-9ae3-2a6564603451&quot;)/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active&quot;]/div[1]/div[1]/article[@class=&quot;m-prodCard -savedLater&quot;]/div[@class=&quot;m-prodCard__row -actions&quot;]/div[@class=&quot;m-prodCard__actions&quot;]/button[@class=&quot;o-savedLaterCarousel__remove&quot;]/img[@class=&quot;o-savedLaterCarousel__removeIcon&quot;]</value>
      <webElementGuid>3245040f-f203-45fa-9bae-448cf38138e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carousel-3b7fb337-cf94-42e8-9ae3-2a6564603451']/div/div/div[2]/div/div/article/div[2]/div/button/img</value>
      <webElementGuid>3ba96ce9-e6f2-48db-adbc-6db5eaaa664f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/article/div[2]/div/button/img</value>
      <webElementGuid>7b60e951-08d0-43fe-bd97-3a8a506d3c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//cdnsc1.melaleuca.com/na/images/common/trash.png']</value>
      <webElementGuid>5ec2ddaa-59bd-416e-8462-a2c4c8401b7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
