<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__o-myAccPopup__icon loaded</name>
   <tag></tag>
   <elementGuidId>cad045eb-56ce-45a5-811e-4b188e68fc32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vApp']/div/header/div[2]/div[5]/div[4]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.o-myAccPopup__icon.loaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8fe9aabe-9b5a-4741-9d14-3082c18b3683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>我的帳戶總覽</value>
      <webElementGuid>0621adb8-57da-42d6-8c5f-0d18dbb2b37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-myAccPopup__icon loaded</value>
      <webElementGuid>09bfdb52-3412-423c-85af-8def7141cbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdnsc1.melaleuca.com/cdn-cgi/image/quality=85/tw-hk/images/header/icon-account-2.png</value>
      <webElementGuid>1235cbf7-69cc-4e89-8287-d37615ae9992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>8ecbb5a0-13b7-4815-801b-799626be73e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vApp&quot;)/div[@class=&quot;bg-gray-25&quot;]/header[@class=&quot;o-siteHeader&quot;]/div[@class=&quot;o-siteHeader__row -main&quot;]/div[@class=&quot;o-siteHeader__col -actions&quot;]/div[@class=&quot;o-myAccPopup&quot;]/button[@class=&quot;o-myAccPopup__btn&quot;]/img[@class=&quot;o-myAccPopup__icon loaded&quot;]</value>
      <webElementGuid>f6eb8656-e508-479d-8c22-9589f2ad0216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vApp']/div/header/div[2]/div[5]/div[4]/button/img</value>
      <webElementGuid>42cec401-df75-43c5-864c-0e28a56aff5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='我的帳戶總覽']</value>
      <webElementGuid>140b8c06-9f93-441d-a514-ce49851ec542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/img</value>
      <webElementGuid>29834978-ae1e-43d0-a1a9-28e7699ab223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '我的帳戶總覽' and @src = 'https://cdnsc1.melaleuca.com/cdn-cgi/image/quality=85/tw-hk/images/header/icon-account-2.png']</value>
      <webElementGuid>88e16fb8-8989-4eea-b7f4-ede04d063cf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
