<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_keyboard_arrow_down</name>
   <tag></tag>
   <elementGuidId>a82e2a04-452e-4048-9578-a4504c772fd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='__VID__49__MelaId_lj2h8dir__accordionId__toggler']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__VID__49__MelaId_lj2h8dir__accordionId__toggler > span.o-checkoutAccordion__icon > span.a-icon.material-icons.-inherit.-transition</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f772c31f-6523-41cb-b2fd-3caa62fdaa80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ee7f0c55-69f4-40fc-acb4-d92128238227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon material-icons -inherit -transition</value>
      <webElementGuid>82a459af-7f06-48ef-9933-8c62290167ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        keyboard_arrow_down
                    </value>
      <webElementGuid>76f9a9a1-de78-426a-b13a-fd0eade8d780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__VID__49__MelaId_lj2h8dir__accordionId__toggler&quot;)/span[@class=&quot;o-checkoutAccordion__icon&quot;]/span[@class=&quot;a-icon material-icons -inherit -transition&quot;]</value>
      <webElementGuid>5ac75a0a-ce20-48b2-b826-3487560c78b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='__VID__49__MelaId_lj2h8dir__accordionId__toggler']/span/span</value>
      <webElementGuid>a2916138-c0bf-4c05-b613-d3c527542ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VisaCard'])[1]/following::span[4]</value>
      <webElementGuid>c2530638-ae94-4be0-9e5b-11b2510c6c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay With'])[1]/following::span[9]</value>
      <webElementGuid>77d2736e-7c23-435b-95f1-4b44cbee9fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VisaCard'])[2]/preceding::span[1]</value>
      <webElementGuid>a22cae94-16e8-4280-a591-6f8caa75f88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::span[11]</value>
      <webElementGuid>0e9b7478-26b8-42a4-9471-b4698e9e8c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/h2/button/span/span</value>
      <webElementGuid>f6d2924c-961d-4bea-ad5b-a62daa39ea2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                        keyboard_arrow_down
                    ' or . = '
                        keyboard_arrow_down
                    ')]</value>
      <webElementGuid>f23aadbb-b847-4575-8b98-73d92c32b6df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
