<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_</name>
   <tag></tag>
   <elementGuidId>b517ac66-0ae6-413c-880c-e3fed3c9b09d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.m-catListMenu__list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CategoryListingComponent']/div/div/div/nav/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>b4f31dde-65e9-49bf-928e-5f8de5940582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-catListMenu__list</value>
      <webElementGuid>6389b87c-f3ba-4b5f-8ffa-ef3e653969d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>所有產品
 日常/推薦套組 活力巔峰營養隨身包</value>
      <webElementGuid>9714c16c-ef95-43f9-ab95-4501f075cd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CategoryListingComponent&quot;)/div[@class=&quot;p-catListing__side&quot;]/div[@class=&quot;p-catListing__menu&quot;]/div[@class=&quot;m-catListMenu&quot;]/nav[@class=&quot;m-catListMenu__nav&quot;]/ul[@class=&quot;m-catListMenu__list&quot;]</value>
      <webElementGuid>977574b9-f106-47c5-bb69-a4fb0654ec38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CategoryListingComponent']/div/div/div/nav/ul</value>
      <webElementGuid>4ad9b5f5-b467-470d-903e-d09de3ca1dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='產品分類'])[1]/following::ul[1]</value>
      <webElementGuid>335338b8-cf45-40db-9338-6c1780aa1e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='營養輔助食品'])[5]/following::ul[1]</value>
      <webElementGuid>b48661e1-6791-4cc9-a8c5-d71a96251834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul</value>
      <webElementGuid>27e4e087-b07c-4596-adae-677b4f4d7fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = '所有產品
 日常/推薦套組 活力巔峰營養隨身包' or . = '所有產品
 日常/推薦套組 活力巔峰營養隨身包')]</value>
      <webElementGuid>3bf4fb24-f0ca-4071-82c3-e90f876c6792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
