<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ (6)</name>
   <tag></tag>
   <elementGuidId>535f6308-ca75-47c5-a140-bd82cbd39f4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dvAdditionalAccountInfo']/b/b/div[3]/div[2]/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '我授權美商亞洲美樂家有限公司使用我以上提供的我的姓名、電子郵件、手機號碼和其他相關聯繫資料，通過電子郵件和或手機短信，發送產品和服務信息，包括滿意度調查、活動、優惠和促銷活動資訊給我。' or . = '我授權美商亞洲美樂家有限公司使用我以上提供的我的姓名、電子郵件、手機號碼和其他相關聯繫資料，通過電子郵件和或手機短信，發送產品和服務信息，包括滿意度調查、活動、優惠和促銷活動資訊給我。')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.field-label-bottom-margin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chkAgreeToTextMessaging</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-label-bottom-margin</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>我授權美商亞洲美樂家有限公司使用我以上提供的我的姓名、電子郵件、手機號碼和其他相關聯繫資料，通過電子郵件和或手機短信，發送產品和服務信息，包括滿意度調查、活動、優惠和促銷活動資訊給我。</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvAdditionalAccountInfo&quot;)/b[1]/b[1]/div[@class=&quot;termsAndConditions&quot;]/div[@class=&quot;inputRow consentToReceiveText&quot;]/label[@class=&quot;field-label-bottom-margin&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvAdditionalAccountInfo']/b/b/div[3]/div[2]/label</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* 表示必填欄位'])[2]/following::label[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/following::label[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='手機訊息 SMS'])[1]/preceding::label[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='電子郵件 Email'])[1]/preceding::label[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='我授權美商亞洲美樂家有限公司使用我以上提供的我的姓名、電子郵件、手機號碼和其他相關聯繫資料，通過電子郵件和或手機短信，發送產品和服務信息，包括滿意度調查、活動、優惠和促銷活動資訊給我。']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
   </webElementXpaths>
</WebElementEntity>
